YACLib: yaclib::detail::fiber::IStackAllocator Class Reference
yaclib::detail::fiber::IStackAllocator Class Reference abstract
Passed to coroutine/fiber constructor, specifies the way in which memory for Stack is Allocated and Released.
#include <stack_allocator.hpp>
Public Member Functions
virtual Allocation Allocate ()=0
virtual void Release (Allocation)=0
virtual void SetMinStackSize (std::size_t bytes)=0
virtual std::size_t GetMinStackSize ()=0
virtual ~IStackAllocator ()=default
Detailed Description
Passed to coroutine/fiber constructor, specifies the way in which memory for Stack is Allocated and Released.
See also
Stack
Definition at line 17 of file stack_allocator.hpp.
Constructor & Destructor Documentation
~IStackAllocator()
virtual yaclib::detail::fiber::IStackAllocator::~IStackAllocator () virtual default
Member Function Documentation
Allocate()
virtual Allocation yaclib::detail::fiber::IStackAllocator::Allocate () pure virtual
Implemented in yaclib::detail::fiber::DefaultAllocator.
GetMinStackSize()
virtual std::size_t yaclib::detail::fiber::IStackAllocator::GetMinStackSize () pure virtual
Implemented in yaclib::detail::fiber::DefaultAllocator.
Release()
virtual void yaclib::detail::fiber::IStackAllocator::Release (Allocation) pure virtual
Implemented in yaclib::detail::fiber::DefaultAllocator.
Referenced by yaclib::detail::fiber::Stack::operator=(), and yaclib::detail::fiber::Stack::~Stack().
SetMinStackSize()
virtual void yaclib::detail::fiber::IStackAllocator::SetMinStackSize (std::size_t bytes) pure virtual
Implemented in yaclib::detail::fiber::DefaultAllocator.
Referenced by yaclib::fiber::SetStackSize().
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/fiber/stack_allocator.hpp