YACLib: yaclib::FutureBase< V, E > Class Template Reference
yaclib::FutureBase< V, E > Class Template Reference
Provides a mechanism to access the result of async operations.
#include <future.hpp>
Public Member Functions
FutureBase (const FutureBase &)=delete
FutureBase & operator= (const FutureBase &)=delete
FutureBase (FutureBase &&other) noexcept=default
FutureBase & operator= (FutureBase &&other) noexcept=default
FutureBase () noexcept=default
The default constructor creates not a Valid Future.
~FutureBase () noexcept
If Future is Valid then call Stop.
bool Valid () const &noexcept
Check if this Future has Promise.
bool Ready () const &noexcept
Check that Result that corresponds to this Future is computed.
void Get () &=delete
void Get () const &&=delete
void Touch () &=delete
void Touch () const &&=delete
const Result< V, E > * Get () const &noexcept
Return copy of Result from Future.
Result< V, E > Get () &&noexcept
const Result< V, E > & Touch () const &noexcept
Result< V, E > Touch () &&noexcept
template<typename Func >
auto Then (IExecutor &e, Func &&f) &&
Attach the continuation func to *this.
void Detach () &&noexcept
Disable calling Stop in destructor.
template<typename Func >
void DetachInline (Func &&f) &&
Attach the final continuation func to *this and Detach *this.
template<typename Func >
void Detach (IExecutor &e, Func &&f) &&
Attach the final continuation func to *this and Detach *this.
detail::ResultCorePtr< V, E > & GetCore () noexcept
Method that get internal Core state.
Protected Member Functions
FutureBase (detail::ResultCorePtr< V, E > core) noexcept
Protected Attributes
detail::ResultCorePtr< V, E > _core
Detailed Description
template<typename V, typename E>
class yaclib::FutureBase< V, E >
Provides a mechanism to access the result of async operations.
Future and Promise are like a Single Producer/Single Consumer one-shot one-element channel. Use the Promise to fulfill the Future.
Definition at line 20 of file future.hpp.
Constructor & Destructor Documentation
FutureBase() [1/4]
template<typename V , typename E > yaclib::FutureBase< V, E >::FutureBase (const FutureBase< V, E > &) delete
FutureBase() [2/4]
template<typename V , typename E > yaclib::FutureBase< V, E >::FutureBase (FutureBase< V, E > && other) default noexcept
FutureBase() [3/4]
template<typename V , typename E > yaclib::FutureBase< V, E >::FutureBase () default noexcept
The default constructor creates not a Valid Future.
Needed only for usability, e.g. instead of std::optional<Future<T>> in containers.
~FutureBase()
template<typename V , typename E > yaclib::FutureBase< V, E >::~FutureBase () inline noexcept
If Future is Valid then call Stop.
Definition at line 42 of file future.hpp.
References yaclib::FutureBase< V, E >::Detach(), and yaclib::FutureBase< V, E >::Valid().
FutureBase() [4/4]
template<typename V , typename E > yaclib::FutureBase< V, E >::FutureBase (detail::ResultCorePtr< V, E > core) inline explicit protected noexcept
Definition at line 184 of file future.hpp.
References yaclib::MakeContract().
Member Function Documentation
Detach() [1/2]
template<typename V , typename E > void yaclib::FutureBase< V, E >::Detach () && inline noexcept
Disable calling Stop in destructor.
Definition at line 141 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, yaclib::MakeContract(), and yaclib::detail::MakeDrop().
Referenced by yaclib::FutureBase< V, E >::~FutureBase().
Detach() [2/2]
template<typename V , typename E > template<typename Func > void yaclib::FutureBase< V, E >::Detach (IExecutor & e, Func && f) && inline
Attach the final continuation func to *this and Detach *this.
The func will be executed on the specified executor.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
e Executor which will Execute the continuation
f A continuation to be attached
Definition at line 168 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, yaclib::IExecutor::Inline, yaclib::MakeContract(), and YACLIB_WARN.
DetachInline()
template<typename V , typename E > template<typename Func > void yaclib::FutureBase< V, E >::DetachInline (Func && f) && inline
Attach the final continuation func to *this and Detach *this.
The func will be executed on Inline executor.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
f A continuation to be attached
Definition at line 155 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, and yaclib::MakeContract().
Get() [1/4]
template<typename V , typename E > Result< V, E > yaclib::FutureBase< V, E >::Get () && inline noexcept
Definition at line 92 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, yaclib::MakeContract(), and yaclib::Wait().
Get() [2/4]
template<typename V , typename E > void yaclib::FutureBase< V, E >::Get () & delete
Get() [3/4]
template<typename V , typename E > void yaclib::FutureBase< V, E >::Get () const && delete
Get() [4/4]
template<typename V , typename E > const Result< V, E > * yaclib::FutureBase< V, E >::Get () const & inline noexcept
Return copy of Result from Future.
If Ready is false return an empty Result. This method is thread-safe and can be called multiple times.
Note
The behavior is undefined if Valid is false before the call to this function.
Returns
Result stored in the shared state
Definition at line 79 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, and yaclib::FutureBase< V, E >::Ready().
GetCore()
template<typename V , typename E > detail::ResultCorePtr< V, E > & yaclib::FutureBase< V, E >::GetCore () inline noexcept
Method that get internal Core state.
Returns
internal Core state ptr
Definition at line 179 of file future.hpp.
References yaclib::FutureBase< V, E >::_core.
operator=() [1/2]
template<typename V , typename E > FutureBase & yaclib::FutureBase< V, E >::operator= (const FutureBase< V, E > &) delete
operator=() [2/2]
template<typename V , typename E > FutureBase & yaclib::FutureBase< V, E >::operator= (FutureBase< V, E > && other) default noexcept
Ready()
template<typename V , typename E > bool yaclib::FutureBase< V, E >::Ready () const & inline noexcept
Check that Result that corresponds to this Future is computed.
Returns
false if the Result of this Future is not computed yet, otherwise true
Definition at line 62 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, yaclib::FutureBase< V, E >::Valid(), and YACLIB_ASSERT.
Referenced by yaclib::FutureBase< V, E >::Get(), yaclib::FutureBase< V, E >::Touch(), and yaclib::FutureBase< V, E >::Touch().
Then()
template<typename V , typename E > template<typename Func > auto yaclib::FutureBase< V, E >::Then (IExecutor & e, Func && f) && inline
Attach the continuation func to *this.
The func will be executed on the specified executor.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
e Executor which will Execute the continuation
f A continuation to be attached
Returns
New FutureOn object associated with the func result
Definition at line 132 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, yaclib::IExecutor::Inline, yaclib::MakeContract(), and YACLIB_WARN.
Touch() [1/4]
template<typename V , typename E > Result< V, E > yaclib::FutureBase< V, E >::Touch () && inline noexcept
Definition at line 116 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, yaclib::MakeContract(), yaclib::FutureBase< V, E >::Ready(), and YACLIB_ASSERT.
Touch() [2/4]
template<typename V , typename E > void yaclib::FutureBase< V, E >::Touch () & delete
Touch() [3/4]
template<typename V , typename E > void yaclib::FutureBase< V, E >::Touch () const && delete
Touch() [4/4]
template<typename V , typename E > const Result< V, E > & yaclib::FutureBase< V, E >::Touch () const & inline noexcept
Definition at line 105 of file future.hpp.
References yaclib::FutureBase< V, E >::_core, yaclib::FutureBase< V, E >::Ready(), and YACLIB_ASSERT.
Valid()
template<typename V , typename E > bool yaclib::FutureBase< V, E >::Valid () const & inline noexcept
Check if this Future has Promise.
Returns
false if this Future is default-constructed or moved to, otherwise true
Examples
simple.cpp.
Definition at line 53 of file future.hpp.
References yaclib::FutureBase< V, E >::_core.
Referenced by yaclib::FutureBase< V, E >::Ready(), TEST(), and yaclib::FutureBase< V, E >::~FutureBase().
Member Data Documentation
_core
template<typename V , typename E > detail::ResultCorePtr<V, E> yaclib::FutureBase< V, E >::_core protected
Definition at line 187 of file future.hpp.
Referenced by yaclib::FutureBase< V, E >::Detach(), yaclib::FutureBase< V, E >::Detach(), yaclib::FutureBase< V, E >::DetachInline(), yaclib::FutureBase< V, E >::Get(), yaclib::FutureBase< V, E >::Get(), yaclib::FutureBase< V, E >::GetCore(), yaclib::FutureBase< V, E >::Ready(), yaclib::FutureBase< V, E >::Then(), yaclib::FutureBase< V, E >::Touch(), yaclib::FutureBase< V, E >::Touch(), and yaclib::FutureBase< V, E >::Valid().
The documentation for this class was generated from the following file:
include/yaclib/async/future.hpp