YACLib: yaclib::detail::AtomicFloatingBase< Impl, T, true > Class Template Reference
yaclib::detail::AtomicFloatingBase< Impl, T, true > Class Template Reference
#include <atomic.hpp>
Public Member Functions
T fetch_add (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
T fetch_add (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T fetch_sub (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
T fetch_sub (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T operator+= (T arg) noexcept
T operator+= (T arg) volatile noexcept
T operator-= (T arg) noexcept
T operator-= (T arg) volatile noexcept
Public Member Functions inherited from yaclib::detail::AtomicBase< Impl, T >
T operator= (T desired) noexcept
T operator= (T desired) volatile noexcept
void store (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
void store (T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T load (std::memory_order order=std::memory_order_seq_cst) const noexcept
T load (std::memory_order order=std::memory_order_seq_cst) const volatile noexcept
operator T () const noexcept
operator T () const volatile noexcept
T exchange (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
T exchange (T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Detailed Description
template<typename Impl, typename T>
class yaclib::detail::AtomicFloatingBase< Impl, T, true >
Definition at line 128 of file atomic.hpp.
Member Function Documentation
fetch_add() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::fetch_add (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 134 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_add() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::fetch_add (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 138 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_sub() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::fetch_sub (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 143 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_sub() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::fetch_sub (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 147 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator+=() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::operator+= (T arg) inline noexcept
Definition at line 152 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator+=() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::operator+= (T arg) volatile inline noexcept
Definition at line 156 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator-=() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::operator-= (T arg) inline noexcept
Definition at line 161 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator-=() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicFloatingBase< Impl, T, true >::operator-= (T arg) volatile inline noexcept
Definition at line 165 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/atomic.hpp