YACLib: yaclib::detail::fiber::AtomicBase< T > Class Template Reference
yaclib::detail::fiber::AtomicBase< T > Class Template Reference
#include <atomic.hpp>
Public Member Functions
void store (T desired, std::memory_order) noexcept
void store (T desired, std::memory_order) volatile noexcept
T load (std::memory_order) const noexcept
T load (std::memory_order) const volatile noexcept
operator T () const noexcept
operator T () const volatile noexcept
T exchange (T desired, std::memory_order) noexcept
T exchange (T desired, std::memory_order) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order, std::memory_order) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order, std::memory_order) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order, std::memory_order) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order, std::memory_order) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order) volatile noexcept
bool is_lock_free () const volatile noexcept
bool is_lock_free () const noexcept
Public Member Functions inherited from yaclib::detail::fiber::AtomicWait< T >
AtomicWait () noexcept=default
constexpr AtomicWait (T desired) noexcept
T operator= (T desired) volatile noexcept
T operator= (T desired) noexcept
bool is_lock_free () const volatile noexcept
bool is_lock_free () const noexcept
Static Public Attributes
static constexpr bool is_always_lock_free
Static Public Attributes inherited from yaclib::detail::fiber::AtomicWait< T >
static constexpr bool is_always_lock_free = true
Protected Member Functions
bool CompareExchangeHelper (T &expected, T desired)
Protected Attributes
T _value
Protected Attributes inherited from yaclib::detail::fiber::AtomicWait< T >
T _value
Detailed Description
template<typename T>
class yaclib::detail::fiber::AtomicBase< T >
Definition at line 10 of file atomic.hpp.
Member Function Documentation
compare_exchange_strong() [1/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong (T & expected, T desired, std::memory_order) inline noexcept
Definition at line 64 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
compare_exchange_strong() [2/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong (T & expected, T desired, std::memory_order) volatile inline noexcept
Definition at line 67 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
compare_exchange_strong() [3/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong (T & expected, T desired, std::memory_order , std::memory_order) inline noexcept
Definition at line 58 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
compare_exchange_strong() [4/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong (T & expected, T desired, std::memory_order , std::memory_order) volatile inline noexcept
Definition at line 61 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
compare_exchange_weak() [1/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak (T & expected, T desired, std::memory_order) inline noexcept
Definition at line 52 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
compare_exchange_weak() [2/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak (T & expected, T desired, std::memory_order) volatile inline noexcept
Definition at line 55 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
compare_exchange_weak() [3/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak (T & expected, T desired, std::memory_order , std::memory_order) inline noexcept
Definition at line 46 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
compare_exchange_weak() [4/4]
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak (T & expected, T desired, std::memory_order , std::memory_order) volatile inline noexcept
Definition at line 49 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), and yaclib::MakeContract().
CompareExchangeHelper()
template<typename T > bool yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper (T & expected, T desired) inline protected
Definition at line 72 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
Referenced by yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong(), yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong(), yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong(), yaclib::detail::fiber::AtomicBase< T >::compare_exchange_strong(), yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak(), yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak(), yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak(), and yaclib::detail::fiber::AtomicBase< T >::compare_exchange_weak().
exchange() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicBase< T >::exchange (T desired, std::memory_order) inline noexcept
Definition at line 39 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
exchange() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicBase< T >::exchange (T desired, std::memory_order) volatile inline noexcept
Definition at line 42 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
is_lock_free() [1/2]
template<typename T > bool yaclib::detail::fiber::AtomicWait< T >::is_lock_free () const inline noexcept
Definition at line 29 of file atomic_wait.hpp.
is_lock_free() [2/2]
template<typename T > bool yaclib::detail::fiber::AtomicWait< T >::is_lock_free () const volatile inline noexcept
Definition at line 25 of file atomic_wait.hpp.
load() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicBase< T >::load (std::memory_order) const inline noexcept
Definition at line 25 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
Referenced by yaclib::detail::fiber::AtomicBase< T >::operator T(), and yaclib::detail::fiber::AtomicBase< T >::operator T().
load() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicBase< T >::load (std::memory_order) const volatile inline noexcept
Definition at line 28 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator T() [1/2]
template<typename T > yaclib::detail::fiber::AtomicBase< T >::operator T () const inline noexcept
Definition at line 32 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::load().
operator T() [2/2]
template<typename T > yaclib::detail::fiber::AtomicBase< T >::operator T () const volatile inline noexcept
Definition at line 35 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::load().
store() [1/2]
template<typename T > void yaclib::detail::fiber::AtomicBase< T >::store (T desired, std::memory_order) inline noexcept
Definition at line 18 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
store() [2/2]
template<typename T > void yaclib::detail::fiber::AtomicBase< T >::store (T desired, std::memory_order) volatile inline noexcept
Definition at line 21 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
Member Data Documentation
_value
template<typename T > T yaclib::detail::fiber::AtomicWait< T >::_value protected
Definition at line 63 of file atomic_wait.hpp.
Referenced by yaclib::detail::fiber::AtomicBase< T >::CompareExchangeHelper(), yaclib::detail::fiber::AtomicBase< T >::exchange(), yaclib::detail::fiber::AtomicBase< T >::exchange(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::fetch_add(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::fetch_add(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_and(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_and(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_or(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_or(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::fetch_sub(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::fetch_sub(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_xor(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_xor(), yaclib::detail::fiber::AtomicBase< T >::load(), yaclib::detail::fiber::AtomicBase< T >::load(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator&=(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator&=(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::operator+=(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::operator+=(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator--(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator--(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator--(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator--(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::operator-=(), yaclib::detail::fiber::AtomicFloatingBase< T, true >::operator-=(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator^=(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator^=(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator|=(), yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator|=(), yaclib::detail::fiber::AtomicBase< T >::store(), and yaclib::detail::fiber::AtomicBase< T >::store().
is_always_lock_free
template<typename T > constexpr bool yaclib::detail::fiber::AtomicWait< T >::is_always_lock_free static constexpr
Definition at line 33 of file atomic_wait.hpp.
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/fiber/atomic.hpp