YACLib: yaclib::detail::fiber::SharedMutex Class Reference
yaclib::detail::fiber::SharedMutex Class Reference
#include <shared_mutex.hpp>
Public Types
using native_handle_type = void *
Public Member Functions
SharedMutex ()=default
~SharedMutex () noexcept=default
SharedMutex (const SharedMutex &)=delete
SharedMutex & operator= (const SharedMutex &)=delete
void lock ()
bool try_lock () noexcept
void unlock () noexcept
void lock_shared ()
bool try_lock_shared ()
void unlock_shared ()
native_handle_type native_handle ()
Protected Member Functions
void LockHelper ()
void SharedLockHelper ()
Protected Attributes
FiberQueue _shared_queue
FiberQueue _exclusive_queue
uint32_t _shared_owners_count {0}
bool _occupied {false}
bool _exclusive_mode {false}
Detailed Description
Definition at line 7 of file shared_mutex.hpp.
Member Typedef Documentation
native_handle_type
using yaclib::detail::fiber::SharedMutex::native_handle_type = void*
Definition at line 25 of file shared_mutex.hpp.
Constructor & Destructor Documentation
SharedMutex() [1/2]
yaclib::detail::fiber::SharedMutex::SharedMutex () default
~SharedMutex()
yaclib::detail::fiber::SharedMutex::~SharedMutex () default noexcept
SharedMutex() [2/2]
yaclib::detail::fiber::SharedMutex::SharedMutex (const SharedMutex &) delete
Member Function Documentation
lock()
void yaclib::detail::fiber::SharedMutex::lock ()
Definition at line 7 of file shared_mutex.cpp.
lock_shared()
void yaclib::detail::fiber::SharedMutex::lock_shared ()
Definition at line 32 of file shared_mutex.cpp.
References _exclusive_mode, _exclusive_queue, _occupied, SharedLockHelper(), and yaclib::detail::fiber::FiberQueue::Wait().
LockHelper()
void yaclib::detail::fiber::SharedMutex::LockHelper () protected
Definition at line 55 of file shared_mutex.cpp.
References _exclusive_mode, and _occupied.
Referenced by try_lock().
native_handle()
SharedMutex::native_handle_type yaclib::detail::fiber::SharedMutex::native_handle () inline
Definition at line 66 of file shared_mutex.cpp.
operator=()
SharedMutex & yaclib::detail::fiber::SharedMutex::operator= (const SharedMutex &) delete
SharedLockHelper()
void yaclib::detail::fiber::SharedMutex::SharedLockHelper () protected
Definition at line 60 of file shared_mutex.cpp.
References _exclusive_mode, _occupied, and _shared_owners_count.
Referenced by lock_shared(), and try_lock_shared().
try_lock()
bool yaclib::detail::fiber::SharedMutex::try_lock () noexcept
Definition at line 14 of file shared_mutex.cpp.
References _occupied, and LockHelper().
try_lock_shared()
bool yaclib::detail::fiber::SharedMutex::try_lock_shared ()
Definition at line 39 of file shared_mutex.cpp.
References _exclusive_mode, _occupied, and SharedLockHelper().
unlock()
void yaclib::detail::fiber::SharedMutex::unlock () noexcept
Definition at line 22 of file shared_mutex.cpp.
References _exclusive_queue, _occupied, _shared_queue, yaclib::detail::fiber::FiberQueue::Empty(), yaclib::detail::GetRandNumber(), yaclib::detail::fiber::FiberQueue::NotifyAll(), yaclib::detail::fiber::FiberQueue::NotifyOne(), and unlock_shared().
unlock_shared()
void yaclib::detail::fiber::SharedMutex::unlock_shared ()
Definition at line 47 of file shared_mutex.cpp.
References _exclusive_queue, _occupied, _shared_owners_count, and yaclib::detail::fiber::FiberQueue::NotifyOne().
Referenced by unlock().
Member Data Documentation
_exclusive_mode
bool yaclib::detail::fiber::SharedMutex::_exclusive_mode {false} protected
Definition at line 37 of file shared_mutex.hpp.
Referenced by lock_shared(), LockHelper(), SharedLockHelper(), and try_lock_shared().
_exclusive_queue
FiberQueue yaclib::detail::fiber::SharedMutex::_exclusive_queue protected
Definition at line 34 of file shared_mutex.hpp.
Referenced by lock_shared(), unlock(), and unlock_shared().
_occupied
bool yaclib::detail::fiber::SharedMutex::_occupied {false} protected
Definition at line 36 of file shared_mutex.hpp.
Referenced by lock_shared(), LockHelper(), SharedLockHelper(), try_lock(), try_lock_shared(), unlock(), and unlock_shared().
_shared_owners_count
uint32_t yaclib::detail::fiber::SharedMutex::_shared_owners_count {0} protected
Definition at line 35 of file shared_mutex.hpp.
Referenced by SharedLockHelper(), and unlock_shared().
_shared_queue
FiberQueue yaclib::detail::fiber::SharedMutex::_shared_queue protected
Definition at line 33 of file shared_mutex.hpp.
Referenced by unlock().
The documentation for this class was generated from the following files:
include/yaclib/fault/detail/fiber/shared_mutex.hpp
src/fault/fiber/shared_mutex.cpp