YACLib: yaclib::detail::Injector Class Reference
yaclib::detail::Injector Class Reference final
#include <injector.hpp>
Public Member Functions
void MaybeInject () noexcept
std::uint32_t GetState () const noexcept
void SetState (std::uint32_t state) noexcept
void Disable () noexcept
void Enable () noexcept
Static Public Member Functions
static void SetFrequency (std::uint32_t freq) noexcept
static void SetSleepTime (std::uint32_t ns) noexcept
static std::uint32_t GetSleepTime () noexcept
static std::uint64_t GetInjectedCount () noexcept
Detailed Description
Definition at line 9 of file injector.hpp.
Member Function Documentation
Disable()
void yaclib::detail::Injector::Disable () noexcept
Definition at line 65 of file injector.cpp.
Enable()
void yaclib::detail::Injector::Enable () noexcept
Definition at line 69 of file injector.cpp.
GetInjectedCount()
std::uint64_t yaclib::detail::Injector::GetInjectedCount () static noexcept
Definition at line 53 of file injector.cpp.
References yaclib::detail::sInjectedCount.
Referenced by yaclib::GetInjectedCount().
GetSleepTime()
std::uint32_t yaclib::detail::Injector::GetSleepTime () static noexcept
Definition at line 49 of file injector.cpp.
References yaclib::detail::sSleepTime.
Referenced by yaclib::GetFaultSleepTime().
GetState()
std::uint32_t yaclib::detail::Injector::GetState () const noexcept
Definition at line 57 of file injector.cpp.
Referenced by yaclib::fiber::GetInjectorState().
MaybeInject()
void yaclib::detail::Injector::MaybeInject () noexcept
Definition at line 13 of file injector.cpp.
References yaclib::detail::GetRandNumber(), yaclib::detail::sInjectedCount, and yaclib::detail::sSleepTime.
Referenced by yaclib::InjectFault().
SetFrequency()
void yaclib::detail::Injector::SetFrequency (std::uint32_t freq) static noexcept
Definition at line 41 of file injector.cpp.
References yaclib::MakeContract(), and yaclib::detail::sYieldFrequency.
Referenced by yaclib::SetFaultFrequency().
SetSleepTime()
void yaclib::detail::Injector::SetSleepTime (std::uint32_t ns) static noexcept
Definition at line 45 of file injector.cpp.
References yaclib::MakeContract(), and yaclib::detail::sSleepTime.
Referenced by yaclib::SetFaultSleepTime().
SetState()
void yaclib::detail::Injector::SetState (std::uint32_t state) noexcept
Definition at line 61 of file injector.cpp.
References yaclib::MakeContract().
Referenced by yaclib::fiber::SetInjectorState().
The documentation for this class was generated from the following files:
include/yaclib/fault/injector.hpp
src/fault/injector.cpp