YACLib: yaclib::detail::fiber::Atomic< U * > Class Template Reference
yaclib::detail::fiber::Atomic< U * > Class Template Reference
#include <atomic.hpp>
Public Member Functions
U * fetch_add (std::ptrdiff_t arg, std::memory_order) noexcept
U * fetch_add (std::ptrdiff_t arg, std::memory_order) volatile noexcept
U * fetch_sub (std::ptrdiff_t arg, std::memory_order) noexcept
U * fetch_sub (std::ptrdiff_t arg, std::memory_order) volatile noexcept
U * operator++ () noexcept
U * operator++ () volatile noexcept
U * operator++ (int) noexcept
U * operator++ (int) volatile noexcept
U * operator-- () noexcept
U * operator-- () volatile noexcept
U * operator-- (int) noexcept
U * operator-- (int) volatile noexcept
U * operator+= (std::ptrdiff_t arg) noexcept
U * operator+= (std::ptrdiff_t arg) volatile noexcept
U * operator-= (std::ptrdiff_t arg) noexcept
U * operator-= (std::ptrdiff_t arg) volatile noexcept
Public Member Functions inherited from yaclib::detail::fiber::AtomicBase< U * >
void store (U * desired, std::memory_order) noexcept
void store (U * desired, std::memory_order) volatile noexcept
U * load (std::memory_order) const noexcept
U * load (std::memory_order) const volatile noexcept
operator U* () const noexcept
operator U* () const volatile noexcept
U * exchange (U * desired, std::memory_order) noexcept
U * exchange (U * desired, std::memory_order) volatile noexcept
bool compare_exchange_weak (U * &expected, U * desired, std::memory_order, std::memory_order) noexcept
bool compare_exchange_weak (U * &expected, U * desired, std::memory_order, std::memory_order) volatile noexcept
bool compare_exchange_weak (U * &expected, U * desired, std::memory_order) noexcept
bool compare_exchange_weak (U * &expected, U * desired, std::memory_order) volatile noexcept
bool compare_exchange_strong (U * &expected, U * desired, std::memory_order, std::memory_order) noexcept
bool compare_exchange_strong (U * &expected, U * desired, std::memory_order, std::memory_order) volatile noexcept
bool compare_exchange_strong (U * &expected, U * desired, std::memory_order) noexcept
bool compare_exchange_strong (U * &expected, U * desired, std::memory_order) volatile noexcept
bool is_lock_free () const volatile noexcept
bool is_lock_free () const noexcept
Public Member Functions inherited from yaclib::detail::fiber::AtomicWait< T >
AtomicWait () noexcept=default
constexpr AtomicWait (T desired) noexcept
T operator= (T desired) volatile noexcept
T operator= (T desired) noexcept
bool is_lock_free () const volatile noexcept
bool is_lock_free () const noexcept
Additional Inherited Members
Static Public Attributes inherited from yaclib::detail::fiber::AtomicBase< U * >
static constexpr bool is_always_lock_free
Static Public Attributes inherited from yaclib::detail::fiber::AtomicWait< T >
static constexpr bool is_always_lock_free = true
Protected Member Functions inherited from yaclib::detail::fiber::AtomicBase< U * >
bool CompareExchangeHelper (U * &expected, U * desired)
Protected Attributes inherited from yaclib::detail::fiber::AtomicBase< U * >
U * _value
Protected Attributes inherited from yaclib::detail::fiber::AtomicWait< T >
T _value
Detailed Description
template<typename U>
class yaclib::detail::fiber::Atomic< U * >
Definition at line 249 of file atomic.hpp.
Member Function Documentation
fetch_add() [1/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::fetch_add (std::ptrdiff_t arg, std::memory_order) inline noexcept
Definition at line 255 of file atomic.hpp.
References yaclib::MakeContract().
fetch_add() [2/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::fetch_add (std::ptrdiff_t arg, std::memory_order) volatile inline noexcept
Definition at line 260 of file atomic.hpp.
References yaclib::MakeContract().
fetch_sub() [1/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::fetch_sub (std::ptrdiff_t arg, std::memory_order) inline noexcept
Definition at line 266 of file atomic.hpp.
References yaclib::MakeContract().
fetch_sub() [2/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::fetch_sub (std::ptrdiff_t arg, std::memory_order) volatile inline noexcept
Definition at line 271 of file atomic.hpp.
References yaclib::MakeContract().
operator++() [1/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator++ () inline noexcept
Definition at line 277 of file atomic.hpp.
operator++() [2/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator++ () volatile inline noexcept
Definition at line 280 of file atomic.hpp.
operator++() [3/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator++ (int) inline noexcept
Definition at line 284 of file atomic.hpp.
operator++() [4/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator++ (int) volatile inline noexcept
Definition at line 287 of file atomic.hpp.
operator+=() [1/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator+= (std::ptrdiff_t arg) inline noexcept
Definition at line 305 of file atomic.hpp.
References yaclib::MakeContract().
operator+=() [2/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator+= (std::ptrdiff_t arg) volatile inline noexcept
Definition at line 308 of file atomic.hpp.
References yaclib::MakeContract().
operator--() [1/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator-- () inline noexcept
Definition at line 291 of file atomic.hpp.
operator--() [2/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator-- () volatile inline noexcept
Definition at line 294 of file atomic.hpp.
operator--() [3/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator-- (int) inline noexcept
Definition at line 298 of file atomic.hpp.
operator--() [4/4]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator-- (int) volatile inline noexcept
Definition at line 301 of file atomic.hpp.
operator-=() [1/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator-= (std::ptrdiff_t arg) inline noexcept
Definition at line 312 of file atomic.hpp.
References yaclib::MakeContract().
operator-=() [2/2]
template<typename U > U * yaclib::detail::fiber::Atomic< U * >::operator-= (std::ptrdiff_t arg) volatile inline noexcept
Definition at line 315 of file atomic.hpp.
References yaclib::MakeContract().
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/fiber/atomic.hpp