YACLib: CalculatorService Class Reference
CalculatorService Class Reference
Public Member Functions
CalculatorService (yaclib::IExecutorPtr e)
yaclib::FutureOn< int > Increment (int value)
yaclib::FutureOn< int > Double (int value)
Detailed Description
Examples
simple.cpp.
Definition at line 111 of file simple.cpp.
Constructor & Destructor Documentation
CalculatorService()
CalculatorService::CalculatorService (yaclib::IExecutorPtr e) inline explicit
Examples
simple.cpp.
Definition at line 113 of file simple.cpp.
Member Function Documentation
Double()
yaclib::FutureOn< int > CalculatorService::Double (int value) inline
Examples
simple.cpp.
Definition at line 122 of file simple.cpp.
References yaclib::Run().
Referenced by TEST().
Increment()
yaclib::FutureOn< int > CalculatorService::Increment (int value) inline
Examples
simple.cpp.
Definition at line 116 of file simple.cpp.
References yaclib::Run().
Referenced by TEST().
The documentation for this class was generated from the following file:
test/example/async/simple.cpp