YACLib: yaclib::detail::ReadyCore< V, E > Class Template Reference
yaclib::detail::ReadyCore< V, E > Class Template Reference
#include <make.hpp>
Public Member Functions
template<typename... Args>
ReadyCore (Args &&... args) noexcept(std::is_nothrow_constructible_v< Result< V, E >, Args &&... >)
void Call () noexcept final
void Drop () noexcept final
InlineCore * Here (InlineCore &) noexcept final
Public Member Functions inherited from yaclib::detail::ResultCore< V, E >
InlineCore * Here (InlineCore &caller) noexcept override
ResultCore () noexcept
template<typename... Args>
ResultCore (Args &&... args) noexcept(std::is_nothrow_constructible_v< Result< V, E >, Args &&... >)
~ResultCore () noexcept override
template<typename... Args>
void Store (Args &&... args) noexcept(std::is_nothrow_constructible_v< Result< V, E >, Args &&... >)
Result< V, E > & Get () noexcept
Public Member Functions inherited from yaclib::detail::BaseCore
void StoreCallback (InlineCore &callback) noexcept
bool Empty () const noexcept
bool SetCallback (InlineCore &callback) noexcept
bool Reset () noexcept
void CallInline (InlineCore &callback) noexcept
template<bool SymmetricTransfer>
Transfer< SymmetricTransfer > SetInline (InlineCore &callback) noexcept
template<bool SymmetricTransfer>
Transfer< SymmetricTransfer > SetResult () noexcept
void MoveExecutorTo (BaseCore &callback) noexcept
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept
Increments reference counter.
virtual void DecRef () noexcept
Decrements reference counter.
virtual ~IRef () noexcept=default
Additional Inherited Members
Public Types inherited from yaclib::detail::BaseCore
enum State : std::uintptr_t { kEmpty = std::uintptr_t{0} , kResult = std::numeric_limits<std::uintptr_t>::max() }
template<bool SymmetricTransfer>
using Transfer = InlineCore *
Public Attributes inherited from yaclib::detail::ResultCore< V, E >
union {
Result< V, E > _result
Callback _self
};
Public Attributes inherited from yaclib::detail::BaseCore
IExecutorPtr _executor {NoRefTag{}, &MakeInline()}
Public Attributes inherited from yaclib::detail::Node
Node * next = nullptr
Protected Member Functions inherited from yaclib::detail::BaseCore
BaseCore (State callback) noexcept
Protected Attributes inherited from yaclib::detail::BaseCore
yaclib_std::atomic_uintptr_t _callback
Detailed Description
template<typename V, typename E>
class yaclib::detail::ReadyCore< V, E >
Definition at line 10 of file make.hpp.
Constructor & Destructor Documentation
ReadyCore()
template<typename V , typename E > template<typename... Args> yaclib::detail::ReadyCore< V, E >::ReadyCore (Args &&... args) inline noexcept
Definition at line 13 of file make.hpp.
References yaclib::MakeContract(), and yaclib::detail::ResultCore< V, E >::Store().
Member Function Documentation
Call()
template<typename V , typename E > void yaclib::detail::ReadyCore< V, E >::Call () inline final virtual noexcept
Reimplemented from yaclib::IFunc.
Definition at line 17 of file make.hpp.
References yaclib::detail::Loop(), and yaclib::MakeContract().
Referenced by yaclib::detail::ReadyCore< V, E >::Drop().
Drop()
template<typename V , typename E > void yaclib::detail::ReadyCore< V, E >::Drop () inline final virtual noexcept
Reimplemented from yaclib::Job.
Definition at line 21 of file make.hpp.
References yaclib::detail::ResultCore< V, E >::_result, yaclib::detail::ReadyCore< V, E >::Call(), yaclib::MakeContract(), and yaclib::detail::ResultCore< V, E >::Store().
Here()
template<typename V , typename E > InlineCore * yaclib::detail::ReadyCore< V, E >::Here (InlineCore &) inline final virtual noexcept
Implements yaclib::detail::InlineCore.
Definition at line 27 of file make.hpp.
References yaclib::MakeContract().
The documentation for this class was generated from the following file:
include/yaclib/lazy/make.hpp