YACLib: yaclib::detail::fiber::Stack Class Reference
yaclib::detail::fiber::Stack Class Reference final
Manages stack memory.
#include <stack.hpp>
Public Member Functions
Stack (IStackAllocator &allocator)
Stack (Stack &&that) noexcept=default
Stack & operator= (Stack &&other) noexcept
Allocation & GetAllocation () noexcept
IStackAllocator & GetAllocator () const noexcept
~Stack ()
Detailed Description
Manages stack memory.
Definition at line 12 of file stack.hpp.
Constructor & Destructor Documentation
Stack() [1/2]
yaclib::detail::fiber::Stack::Stack (IStackAllocator & allocator) inline explicit
Definition at line 14 of file stack.hpp.
Stack() [2/2]
yaclib::detail::fiber::Stack::Stack (Stack && that) default noexcept
~Stack()
yaclib::detail::fiber::Stack::~Stack () inline
Definition at line 37 of file stack.hpp.
References yaclib::detail::fiber::IStackAllocator::Release().
Member Function Documentation
GetAllocation()
Allocation & yaclib::detail::fiber::Stack::GetAllocation () inline noexcept
Definition at line 29 of file stack.hpp.
Referenced by yaclib::detail::fiber::Fiber< Args >::Fiber(), and operator=().
GetAllocator()
IStackAllocator & yaclib::detail::fiber::Stack::GetAllocator () const inline noexcept
Definition at line 33 of file stack.hpp.
operator=()
Stack & yaclib::detail::fiber::Stack::operator= (Stack && other) inline noexcept
Definition at line 19 of file stack.hpp.
References GetAllocation(), and yaclib::detail::fiber::IStackAllocator::Release().
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/fiber/stack.hpp