YACLib: yaclib::detail::fiber::FiberBase Class Reference
yaclib::detail::fiber::FiberBase Class Reference
#include <fiber_base.hpp>
Public Types
using Id = uint64_t
Public Member Functions
FiberBase ()
void SetJoiningFiber (FiberBase *joining_fiber) noexcept
Id GetId () const noexcept
void Resume ()
void Suspend ()
FiberState GetState () noexcept
void SetState (FiberState state) noexcept
void SetThreadlikeInstanceDead () noexcept
bool IsThreadlikeInstanceAlive () const noexcept
void * GetTls (uint64_t id, std::unordered_map< uint64_t, void * > &defaults)
void SetTls (uint64_t id, void *value)
virtual ~FiberBase ()=default
Public Member Functions inherited from yaclib::detail::fiber::Node
bool Erase ()
Static Public Member Functions
static IStackAllocator & GetAllocator () noexcept
Protected Member Functions
void Start ()
void Exit ()
Protected Attributes
ExecutionContext _context {}
Stack _stack
std::exception_ptr _exception
Additional Inherited Members
Public Attributes inherited from yaclib::detail::fiber::Node
Node * prev {this}
Node * next {this}
Detailed Description
Definition at line 27 of file fiber_base.hpp.
Member Typedef Documentation
Id
using yaclib::detail::fiber::FiberBase::Id = uint64_t
Definition at line 29 of file fiber_base.hpp.
Constructor & Destructor Documentation
FiberBase()
yaclib::detail::fiber::FiberBase::FiberBase ()
Definition at line 11 of file fiber_base.cpp.
~FiberBase()
virtual yaclib::detail::fiber::FiberBase::~FiberBase () virtual default
Member Function Documentation
Exit()
void yaclib::detail::fiber::FiberBase::Exit () protected
Definition at line 41 of file fiber_base.cpp.
References _context, yaclib::detail::fiber::Completed, yaclib::detail::fiber::ExecutionContext::Exit(), and yaclib::detail::fiber::ScheduleFiber().
GetAllocator()
IStackAllocator & yaclib::detail::fiber::FiberBase::GetAllocator () static noexcept
Definition at line 78 of file fiber_base.cpp.
Referenced by yaclib::fiber::SetStackSize().
GetId()
FiberBase::Id yaclib::detail::fiber::FiberBase::GetId () const noexcept
Definition at line 14 of file fiber_base.cpp.
Referenced by yaclib::detail::fiber::Thread::get_id(), yaclib::fault::Scheduler::GetId(), and yaclib::detail::fiber::Thread::joinable().
GetState()
FiberState yaclib::detail::fiber::FiberBase::GetState () noexcept
Definition at line 49 of file fiber_base.cpp.
Referenced by yaclib::detail::fiber::Thread::join().
GetTls()
void * yaclib::detail::fiber::FiberBase::GetTls (uint64_t id, std::unordered_map< uint64_t, void * > & defaults)
Definition at line 65 of file fiber_base.cpp.
IsThreadlikeInstanceAlive()
bool yaclib::detail::fiber::FiberBase::IsThreadlikeInstanceAlive () const noexcept
Definition at line 61 of file fiber_base.cpp.
Resume()
void yaclib::detail::fiber::FiberBase::Resume ()
Definition at line 18 of file fiber_base.cpp.
References _context, _exception, yaclib::detail::fiber::Completed, yaclib::detail::fiber::Running, and yaclib::detail::fiber::ExecutionContext::SwitchTo().
SetJoiningFiber()
void yaclib::detail::fiber::FiberBase::SetJoiningFiber (FiberBase * joining_fiber) noexcept
Definition at line 53 of file fiber_base.cpp.
Referenced by yaclib::detail::fiber::Thread::join().
SetState()
void yaclib::detail::fiber::FiberBase::SetState (FiberState state) noexcept
Definition at line 82 of file fiber_base.cpp.
Referenced by yaclib::fault::Scheduler::Schedule().
SetThreadlikeInstanceDead()
void yaclib::detail::fiber::FiberBase::SetThreadlikeInstanceDead () noexcept
Definition at line 57 of file fiber_base.cpp.
SetTls()
void yaclib::detail::fiber::FiberBase::SetTls (uint64_t id, void * value)
Definition at line 74 of file fiber_base.cpp.
Start()
void yaclib::detail::fiber::FiberBase::Start () protected
Definition at line 37 of file fiber_base.cpp.
References _context, and yaclib::detail::fiber::ExecutionContext::Start().
Referenced by yaclib::detail::fiber::Fiber< Args >::Trampoline().
Suspend()
void yaclib::detail::fiber::FiberBase::Suspend ()
Definition at line 32 of file fiber_base.cpp.
References _context, yaclib::detail::fiber::Suspended, and yaclib::detail::fiber::ExecutionContext::SwitchTo().
Referenced by yaclib::fault::Scheduler::Suspend().
Member Data Documentation
_context
ExecutionContext yaclib::detail::fiber::FiberBase::_context {} protected
Definition at line 61 of file fiber_base.hpp.
Referenced by Exit(), yaclib::detail::fiber::Fiber< Args >::Fiber(), Resume(), Start(), and Suspend().
_exception
std::exception_ptr yaclib::detail::fiber::FiberBase::_exception protected
Definition at line 63 of file fiber_base.hpp.
Referenced by Resume().
_stack
Stack yaclib::detail::fiber::FiberBase::_stack protected
Definition at line 62 of file fiber_base.hpp.
Referenced by yaclib::detail::fiber::Fiber< Args >::Fiber().
The documentation for this class was generated from the following files:
include/yaclib/fault/detail/fiber/fiber_base.hpp
src/fault/fiber/fiber_base.cpp