YACLib: yaclib::OneShotEventAwaiter Class Reference
yaclib::OneShotEventAwaiter Class Reference final
#include <oneshot_event.hpp>
Public Member Functions
OneShotEventAwaiter (IExecutor &executor, OneShotEvent &event) noexcept
bool await_ready () const noexcept
template<typename Promise >
bool await_suspend (yaclib_std::coroutine_handle< Promise > handle) noexcept
void await_resume () const noexcept
void Call () noexcept final
void Drop () noexcept final
Public Member Functions inherited from yaclib::detail::NopeCounter< Job >
void IncRef () noexcept final
void DecRef () noexcept final
Friends
class OneShotEvent
Detailed Description
Definition at line 39 of file oneshot_event.hpp.
Constructor & Destructor Documentation
OneShotEventAwaiter()
yaclib::OneShotEventAwaiter::OneShotEventAwaiter (IExecutor & executor, OneShotEvent & event) inline noexcept
Definition at line 41 of file oneshot_event.hpp.
Member Function Documentation
await_ready()
bool yaclib::OneShotEventAwaiter::await_ready () const inline noexcept
Definition at line 44 of file oneshot_event.hpp.
References yaclib::OneShotEvent::Ready().
await_resume()
void yaclib::OneShotEventAwaiter::await_resume () const inline noexcept
Definition at line 52 of file oneshot_event.hpp.
await_suspend()
template<typename Promise > bool yaclib::OneShotEventAwaiter::await_suspend (yaclib_std::coroutine_handle< Promise > handle) inline noexcept
Definition at line 48 of file oneshot_event.hpp.
Call()
void yaclib::OneShotEventAwaiter::Call () inline final noexcept
Definition at line 55 of file oneshot_event.hpp.
References yaclib::IExecutor::Submit().
Drop()
void yaclib::OneShotEventAwaiter::Drop () inline final noexcept
Definition at line 59 of file oneshot_event.hpp.
References yaclib::detail::InlineCore::Drop().
Friends And Related Function Documentation
OneShotEvent
friend class OneShotEvent friend
Definition at line 64 of file oneshot_event.hpp.
The documentation for this class was generated from the following file:
include/yaclib/coroutine/oneshot_event.hpp