YACLib: yaclib::detail::fiber::AtomicIntegralBase< T, true > Class Template Reference
yaclib::detail::fiber::AtomicIntegralBase< T, true > Class Template Reference
#include <atomic.hpp>
Public Member Functions
T fetch_and (T arg, std::memory_order) noexcept
T fetch_and (T arg, std::memory_order) volatile noexcept
T fetch_or (T arg, std::memory_order) noexcept
T fetch_or (T arg, std::memory_order) volatile noexcept
T fetch_xor (T arg, std::memory_order) noexcept
T fetch_xor (T arg, std::memory_order) volatile noexcept
T operator++ () noexcept
T operator++ () volatile noexcept
T operator++ (int) noexcept
T operator++ (int) volatile noexcept
T operator-- () noexcept
T operator-- () volatile noexcept
T operator-- (int) noexcept
T operator-- (int) volatile noexcept
T operator&= (T arg) noexcept
T operator&= (T arg) volatile noexcept
T operator|= (T arg) noexcept
T operator|= (T arg) volatile noexcept
T operator^= (T arg) noexcept
T operator^= (T arg) volatile noexcept
Public Member Functions inherited from yaclib::detail::fiber::AtomicFloatingBase< T, true >
T fetch_add (T arg, std::memory_order) noexcept
T fetch_add (T arg, std::memory_order) volatile noexcept
T fetch_sub (T arg, std::memory_order) noexcept
T fetch_sub (T arg, std::memory_order) volatile noexcept
T operator+= (T arg) noexcept
T operator+= (T arg) volatile noexcept
T operator-= (T arg) noexcept
T operator-= (T arg) volatile noexcept
Public Member Functions inherited from yaclib::detail::fiber::AtomicBase< T >
void store (T desired, std::memory_order) noexcept
void store (T desired, std::memory_order) volatile noexcept
T load (std::memory_order) const noexcept
T load (std::memory_order) const volatile noexcept
operator T () const noexcept
operator T () const volatile noexcept
T exchange (T desired, std::memory_order) noexcept
T exchange (T desired, std::memory_order) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order, std::memory_order) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order, std::memory_order) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order, std::memory_order) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order, std::memory_order) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order) volatile noexcept
bool is_lock_free () const volatile noexcept
bool is_lock_free () const noexcept
Public Member Functions inherited from yaclib::detail::fiber::AtomicWait< T >
AtomicWait () noexcept=default
constexpr AtomicWait (T desired) noexcept
T operator= (T desired) volatile noexcept
T operator= (T desired) noexcept
bool is_lock_free () const volatile noexcept
bool is_lock_free () const noexcept
Protected Attributes
T _value
Protected Attributes inherited from yaclib::detail::fiber::AtomicFloatingBase< T, true >
T _value
Protected Attributes inherited from yaclib::detail::fiber::AtomicBase< T >
T _value
Protected Attributes inherited from yaclib::detail::fiber::AtomicWait< T >
T _value
Additional Inherited Members
Static Public Attributes inherited from yaclib::detail::fiber::AtomicBase< T >
static constexpr bool is_always_lock_free
Static Public Attributes inherited from yaclib::detail::fiber::AtomicWait< T >
static constexpr bool is_always_lock_free = true
Protected Member Functions inherited from yaclib::detail::fiber::AtomicBase< T >
bool CompareExchangeHelper (T &expected, T desired)
Detailed Description
template<typename T>
class yaclib::detail::fiber::AtomicIntegralBase< T, true >
Definition at line 148 of file atomic.hpp.
Member Function Documentation
fetch_and() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_and (T arg, std::memory_order) inline noexcept
Definition at line 154 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
fetch_and() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_and (T arg, std::memory_order) volatile inline noexcept
Definition at line 159 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
fetch_or() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_or (T arg, std::memory_order) inline noexcept
Definition at line 165 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
fetch_or() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_or (T arg, std::memory_order) volatile inline noexcept
Definition at line 170 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
fetch_xor() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_xor (T arg, std::memory_order) inline noexcept
Definition at line 176 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
fetch_xor() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::fetch_xor (T arg, std::memory_order) volatile inline noexcept
Definition at line 181 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
operator&=() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator&= (T arg) inline noexcept
Definition at line 215 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
operator&=() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator&= (T arg) volatile inline noexcept
Definition at line 218 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
operator++() [1/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++ () inline noexcept
Definition at line 187 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator++() [2/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++ () volatile inline noexcept
Definition at line 190 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator++() [3/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++ (int) inline noexcept
Definition at line 194 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator++() [4/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator++ (int) volatile inline noexcept
Definition at line 197 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator--() [1/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator-- () inline noexcept
Definition at line 201 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator--() [2/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator-- () volatile inline noexcept
Definition at line 204 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator--() [3/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator-- (int) inline noexcept
Definition at line 208 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator--() [4/4]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator-- (int) volatile inline noexcept
Definition at line 211 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value.
operator^=() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator^= (T arg) inline noexcept
Definition at line 229 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
operator^=() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator^= (T arg) volatile inline noexcept
Definition at line 232 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
operator|=() [1/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator|= (T arg) inline noexcept
Definition at line 222 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
operator|=() [2/2]
template<typename T > T yaclib::detail::fiber::AtomicIntegralBase< T, true >::operator|= (T arg) volatile inline noexcept
Definition at line 225 of file atomic.hpp.
References yaclib::detail::fiber::AtomicBase< T >::_value, and yaclib::MakeContract().
Member Data Documentation
_value
template<typename T > T yaclib::detail::fiber::AtomicWait< T >::_value protected
Definition at line 136 of file atomic_wait.hpp.
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/fiber/atomic.hpp