YACLib: yaclib::SharedFutureBase< V, E > Class Template Reference
yaclib::SharedFutureBase< V, E > Class Template Reference
#include <shared_future.hpp>
Public Types
using Handle = detail::SharedHandle
using Core = detail::SharedCore< V, E >
Public Member Functions
SharedFutureBase ()=default
bool Valid () const noexcept
bool Ready () const noexcept
Result< V, E > Get () &&noexcept
void Get () const &&=delete
const Result< V, E > & Get () const &noexcept
Result< V, E > Touch () &&noexcept
void Touch () const &&=delete
const Result< V, E > & Touch () const &noexcept
template<typename Func >
auto Then (IExecutor &e, Func &&f) const
void Detach () &&noexcept
template<typename Func >
void SubscribeInline (Func &&f) const
template<typename Func >
void Subscribe (IExecutor &e, Func &&f) const
detail::SharedCorePtr< V, E > & GetCore () noexcept
const detail::SharedCorePtr< V, E > & GetCore () const noexcept
detail::SharedHandle GetHandle () const noexcept
Protected Member Functions
SharedFutureBase (detail::SharedCorePtr< V, E > core) noexcept
Protected Attributes
detail::SharedCorePtr< V, E > _core
Detailed Description
template<typename V, typename E>
class yaclib::SharedFutureBase< V, E >
Definition at line 14 of file shared_future.hpp.
Member Typedef Documentation
Core
template<typename V , typename E > using yaclib::SharedFutureBase< V, E >::Core = detail::SharedCore<V, E>
Definition at line 105 of file shared_future.hpp.
Handle
template<typename V , typename E > using yaclib::SharedFutureBase< V, E >::Handle = detail::SharedHandle
Definition at line 104 of file shared_future.hpp.
Constructor & Destructor Documentation
SharedFutureBase() [1/2]
template<typename V , typename E > yaclib::SharedFutureBase< V, E >::SharedFutureBase () default
SharedFutureBase() [2/2]
template<typename V , typename E > yaclib::SharedFutureBase< V, E >::SharedFutureBase (detail::SharedCorePtr< V, E > core) inline explicit protected noexcept
Definition at line 112 of file shared_future.hpp.
Member Function Documentation
Detach()
template<typename V , typename E > void yaclib::SharedFutureBase< V, E >::Detach () && inline noexcept
Definition at line 78 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core.
Get() [1/3]
template<typename V , typename E > Result< V, E > yaclib::SharedFutureBase< V, E >::Get () && inline noexcept
Definition at line 34 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, yaclib::SharedFutureBase< V, E >::Valid(), yaclib::Wait(), and YACLIB_ASSERT.
Get() [2/3]
template<typename V , typename E > void yaclib::SharedFutureBase< V, E >::Get () const && delete
Get() [3/3]
template<typename V , typename E > const Result< V, E > & yaclib::SharedFutureBase< V, E >::Get () const & inline noexcept
Definition at line 46 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, yaclib::SharedFutureBase< V, E >::Valid(), yaclib::Wait(), and YACLIB_ASSERT.
GetCore() [1/2]
template<typename V , typename E > const detail::SharedCorePtr< V, E > & yaclib::SharedFutureBase< V, E >::GetCore () const inline noexcept
Definition at line 100 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core.
GetCore() [2/2]
template<typename V , typename E > detail::SharedCorePtr< V, E > & yaclib::SharedFutureBase< V, E >::GetCore () inline noexcept
Definition at line 96 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core.
Referenced by yaclib::Split().
GetHandle()
template<typename V , typename E > detail::SharedHandle yaclib::SharedFutureBase< V, E >::GetHandle () const inline noexcept
Definition at line 107 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core.
Ready()
template<typename V , typename E > bool yaclib::SharedFutureBase< V, E >::Ready () const inline noexcept
Definition at line 29 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, yaclib::SharedFutureBase< V, E >::Valid(), and YACLIB_ASSERT.
Referenced by yaclib::SharedFutureBase< V, E >::Touch(), and yaclib::SharedFutureBase< V, E >::Touch().
Subscribe()
template<typename V , typename E > template<typename Func > void yaclib::SharedFutureBase< V, E >::Subscribe (IExecutor & e, Func && f) const inline
Definition at line 89 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, yaclib::IExecutor::Inline, yaclib::MakeContract(), and YACLIB_WARN.
SubscribeInline()
template<typename V , typename E > template<typename Func > void yaclib::SharedFutureBase< V, E >::SubscribeInline (Func && f) const inline
Definition at line 83 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, and yaclib::MakeContract().
Then()
template<typename V , typename E > template<typename Func > auto yaclib::SharedFutureBase< V, E >::Then (IExecutor & e, Func && f) const inline
Definition at line 71 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, yaclib::IExecutor::Inline, yaclib::MakeContract(), and YACLIB_WARN.
Touch() [1/3]
template<typename V , typename E > Result< V, E > yaclib::SharedFutureBase< V, E >::Touch () && inline noexcept
Definition at line 52 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, yaclib::SharedFutureBase< V, E >::Ready(), yaclib::SharedFutureBase< V, E >::Valid(), and YACLIB_ASSERT.
Touch() [2/3]
template<typename V , typename E > void yaclib::SharedFutureBase< V, E >::Touch () const && delete
Touch() [3/3]
template<typename V , typename E > const Result< V, E > & yaclib::SharedFutureBase< V, E >::Touch () const & inline noexcept
Definition at line 64 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core, yaclib::SharedFutureBase< V, E >::Ready(), yaclib::SharedFutureBase< V, E >::Valid(), and YACLIB_ASSERT.
Valid()
template<typename V , typename E > bool yaclib::SharedFutureBase< V, E >::Valid () const inline noexcept
Definition at line 25 of file shared_future.hpp.
References yaclib::SharedFutureBase< V, E >::_core.
Referenced by yaclib::SharedFutureBase< V, E >::Get(), yaclib::SharedFutureBase< V, E >::Get(), yaclib::SharedFutureBase< V, E >::Ready(), yaclib::SharedFutureBase< V, E >::Touch(), and yaclib::SharedFutureBase< V, E >::Touch().
Member Data Documentation
_core
template<typename V , typename E > detail::SharedCorePtr<V, E> yaclib::SharedFutureBase< V, E >::_core protected
Definition at line 115 of file shared_future.hpp.
Referenced by yaclib::SharedFutureBase< V, E >::Detach(), yaclib::SharedFutureBase< V, E >::Get(), yaclib::SharedFutureBase< V, E >::Get(), yaclib::SharedFutureBase< V, E >::GetCore(), yaclib::SharedFutureBase< V, E >::GetCore(), yaclib::SharedFutureBase< V, E >::GetHandle(), yaclib::SharedFutureBase< V, E >::Ready(), yaclib::SharedFutureBase< V, E >::Subscribe(), yaclib::SharedFutureBase< V, E >::SubscribeInline(), yaclib::SharedFutureBase< V, E >::Then(), yaclib::SharedFutureBase< V, E >::Touch(), yaclib::SharedFutureBase< V, E >::Touch(), and yaclib::SharedFutureBase< V, E >::Valid().
The documentation for this class was generated from the following file:
include/yaclib/async/shared_future.hpp