YACLib: yaclib::detail::GuardState Class Reference
yaclib::detail::GuardState Class Reference
#include <guard_state.hpp>
Public Member Functions
GuardState () noexcept=default
GuardState (void *ptr, bool owns) noexcept
GuardState (GuardState &&other) noexcept
GuardState & operator= (GuardState &&other) noexcept
void Swap (GuardState &other) noexcept
void * Ptr () const
bool Owns () const noexcept
void * LockState () noexcept
void * UnlockState () noexcept
void * ReleaseState () noexcept
Protected Attributes
std::uintptr_t _state = 0
Detailed Description
Definition at line 9 of file guard_state.hpp.
Constructor & Destructor Documentation
GuardState() [1/3]
yaclib::detail::GuardState::GuardState () default noexcept
GuardState() [2/3]
yaclib::detail::GuardState::GuardState (void * ptr, bool owns) inline explicit noexcept
Definition at line 15 of file guard_state.hpp.
References yaclib::MakeContract().
GuardState() [3/3]
yaclib::detail::GuardState::GuardState (GuardState && other) inline noexcept
Definition at line 19 of file guard_state.hpp.
References yaclib::MakeContract().
Member Function Documentation
LockState()
void * yaclib::detail::GuardState::LockState () inline noexcept
Definition at line 40 of file guard_state.hpp.
References _state, Owns(), Ptr(), and YACLIB_DEBUG.
Referenced by yaclib::detail::Guard< M, Shared >::Lock(), and yaclib::detail::Guard< M, Shared >::TryLock().
operator=()
GuardState & yaclib::detail::GuardState::operator= (GuardState && other) inline noexcept
Definition at line 23 of file guard_state.hpp.
References yaclib::MakeContract(), and Swap().
Owns()
bool yaclib::detail::GuardState::Owns () const inline noexcept
Definition at line 36 of file guard_state.hpp.
References _state.
Referenced by LockState(), yaclib::detail::Guard< M, Shared >::OwnsLock(), and UnlockState().
Ptr()
void * yaclib::detail::GuardState::Ptr () const inline
Definition at line 32 of file guard_state.hpp.
References _state.
Referenced by LockState(), yaclib::detail::Guard< M, Shared >::Mutex(), ReleaseState(), and UnlockState().
ReleaseState()
void * yaclib::detail::GuardState::ReleaseState () inline noexcept
Definition at line 52 of file guard_state.hpp.
References _state, yaclib::MakeContract(), and Ptr().
Referenced by yaclib::detail::Guard< M, Shared >::Release().
Swap()
void yaclib::detail::GuardState::Swap (GuardState & other) inline noexcept
Definition at line 28 of file guard_state.hpp.
References _state, and yaclib::MakeContract().
Referenced by operator=().
UnlockState()
void * yaclib::detail::GuardState::UnlockState () inline noexcept
Definition at line 46 of file guard_state.hpp.
References _state, Owns(), Ptr(), and YACLIB_DEBUG.
Referenced by yaclib::detail::Guard< M, Shared >::TryLock(), yaclib::detail::Guard< M, Shared >::Unlock(), yaclib::detail::Guard< M, Shared >::UnlockHere(), and yaclib::detail::Guard< M, Shared >::UnlockOn().
Member Data Documentation
_state
std::uintptr_t yaclib::detail::GuardState::_state = 0 protected
Definition at line 59 of file guard_state.hpp.
Referenced by LockState(), Owns(), Ptr(), ReleaseState(), yaclib::detail::Guard< M, Shared >::Swap(), Swap(), and UnlockState().
The documentation for this class was generated from the following file:
include/yaclib/coro/detail/guard_state.hpp