YACLib: yaclib::detail::fiber::BiList Class Reference
yaclib::detail::fiber::BiList Class Reference final
#include <bidirectional_intrusive_list.hpp>
Public Member Functions
BiList & operator= (const BiList &)=delete
BiList & operator= (BiList &&) noexcept
BiList (const BiList &)=delete
BiList () noexcept=default
BiList (BiList &&) noexcept
void PushBack (Node *node) noexcept
void PushAll (BiList &&other) noexcept
Node * PopBack () noexcept
bool Empty () const noexcept
Node * GetElement (std::size_t ind, bool reversed) const noexcept
Detailed Description
Definition at line 16 of file bidirectional_intrusive_list.hpp.
Constructor & Destructor Documentation
BiList() [1/3]
yaclib::detail::fiber::BiList::BiList (const BiList &) delete
BiList() [2/3]
yaclib::detail::fiber::BiList::BiList () default noexcept
BiList() [3/3]
yaclib::detail::fiber::BiList::BiList (BiList && other) noexcept
Definition at line 19 of file bidirectional_intrusive_list.cpp.
References yaclib::MakeContract().
Member Function Documentation
Empty()
bool yaclib::detail::fiber::BiList::Empty () const noexcept
Definition at line 15 of file bidirectional_intrusive_list.cpp.
References yaclib::detail::fiber::Node::next.
Referenced by yaclib::detail::fiber::FiberQueue::Empty(), yaclib::detail::fiber::FiberQueue::NotifyOne(), and yaclib::detail::fiber::FiberQueue::~FiberQueue().
GetElement()
Node * yaclib::detail::fiber::BiList::GetElement (std::size_t ind, bool reversed) const noexcept
Definition at line 32 of file bidirectional_intrusive_list.cpp.
References yaclib::MakeContract(), yaclib::detail::fiber::Node::next, and yaclib::detail::fiber::Node::prev.
operator=() [1/2]
BiList & yaclib::detail::fiber::BiList::operator= (BiList && other) noexcept
Definition at line 77 of file bidirectional_intrusive_list.cpp.
References yaclib::MakeContract().
operator=() [2/2]
BiList & yaclib::detail::fiber::BiList::operator= (const BiList &) delete
PopBack()
Node * yaclib::detail::fiber::BiList::PopBack () noexcept
Definition at line 26 of file bidirectional_intrusive_list.cpp.
References yaclib::detail::fiber::Node::Erase(), yaclib::MakeContract(), and yaclib::detail::fiber::Node::prev.
PushAll()
void yaclib::detail::fiber::BiList::PushAll (BiList && other) noexcept
Definition at line 93 of file bidirectional_intrusive_list.cpp.
References yaclib::MakeContract().
PushBack()
void yaclib::detail::fiber::BiList::PushBack (Node * node) noexcept
Definition at line 7 of file bidirectional_intrusive_list.cpp.
References yaclib::MakeContract(), and YACLIB_DEBUG.
Referenced by yaclib::fault::Scheduler::RescheduleCurrent(), yaclib::fault::Scheduler::Schedule(), yaclib::detail::fiber::FiberQueue::Wait(), and yaclib::detail::fiber::FiberQueue::Wait().
The documentation for this class was generated from the following files:
include/yaclib/fault/detail/fiber/bidirectional_intrusive_list.hpp
src/fault/fiber/bidirectional_intrusive_list.cpp