YACLib: yaclib::AwaitGroup Class Reference
yaclib::AwaitGroup Class Reference final
#include <await_group.hpp>
Public Member Functions
AwaitGroup ()=default
void Add (std::size_t count=1) noexcept
void Done (std::size_t count=1) noexcept
template<bool NeedAdd = true, typename... V, typename... E>
YACLIB_INLINE void Add (FutureBase< V, E > &... futures)
template<bool NeedAdd = true, typename It >
YACLIB_INLINE std::enable_if_t<!is_future_base_v< It >, void > Add (It begin, It end)
template<bool NeedAdd = true, typename It >
YACLIB_INLINE void Add (It begin, std::size_t count)
auto Await (IExecutor &exec=CurrentThreadPool())
void Wait ()
auto operator co_await ()
void Reset () noexcept
template<bool NeedAdd, typename Iterator >
void Add (Iterator it, std::size_t count)
Detailed Description
Definition at line 10 of file await_group.hpp.
Constructor & Destructor Documentation
AwaitGroup()
yaclib::AwaitGroup::AwaitGroup () default
Member Function Documentation
Add() [1/5]
template<bool NeedAdd, typename... V, typename... E> YACLIB_INLINE void yaclib::AwaitGroup::Add (FutureBase< V, E > &... futures)
Definition at line 45 of file await_group_impl.hpp.
References yaclib::FutureBase< V, E >::GetCore().
Add() [2/5]
template<bool NeedAdd, typename It > YACLIB_INLINE std::enable_if_t<!is_future_base_v< It >, void > yaclib::AwaitGroup::Add (It begin, It end)
Definition at line 50 of file await_group_impl.hpp.
Add() [3/5]
template<bool NeedAdd = true, typename It > YACLIB_INLINE void yaclib::AwaitGroup::Add (It begin, std::size_t count)
Add() [4/5]
template<bool NeedAdd, typename Iterator > void yaclib::AwaitGroup::Add (Iterator it, std::size_t count)
Definition at line 16 of file await_group_impl.hpp.
Add() [5/5]
void yaclib::AwaitGroup::Add (std::size_t count = 1) inline noexcept
Definition at line 13 of file await_group.hpp.
Await()
auto yaclib::AwaitGroup::Await (IExecutor & exec = CurrentThreadPool()) inline
Definition at line 28 of file await_group.hpp.
Referenced by operator co_await().
Done()
void yaclib::AwaitGroup::Done (std::size_t count = 1) inline noexcept
Definition at line 16 of file await_group.hpp.
operator co_await()
auto yaclib::AwaitGroup::operator co_await () inline
Definition at line 36 of file await_group.hpp.
References Await(), and YACLIB_WARN.
Reset()
void yaclib::AwaitGroup::Reset () inline noexcept
Definition at line 41 of file await_group.hpp.
Wait()
void yaclib::AwaitGroup::Wait () inline
Definition at line 32 of file await_group.hpp.
References yaclib::Wait().
Referenced by yaclib::Wait().
The documentation for this class was generated from the following files:
include/yaclib/coroutine/await_group.hpp
include/yaclib/coroutine/detail/await_group_impl.hpp