YACLib: yaclib::detail::fiber::ThreadLocalPtrProxy< Type > Class Template Reference
yaclib::detail::fiber::ThreadLocalPtrProxy< Type > Class Template Reference final
#include <thread_local_proxy.hpp>
Public Member Functions
ThreadLocalPtrProxy () noexcept
ThreadLocalPtrProxy (Type *value) noexcept
ThreadLocalPtrProxy (ThreadLocalPtrProxy &&other) noexcept
ThreadLocalPtrProxy (const ThreadLocalPtrProxy &other) noexcept
ThreadLocalPtrProxy & operator= (Type *value) noexcept
ThreadLocalPtrProxy & operator= (ThreadLocalPtrProxy &&other) noexcept
ThreadLocalPtrProxy & operator= (const ThreadLocalPtrProxy &other) noexcept
template<typename U >
ThreadLocalPtrProxy (ThreadLocalPtrProxy< U > &&other) noexcept
template<typename U >
ThreadLocalPtrProxy (const ThreadLocalPtrProxy< U > &other) noexcept
template<typename U >
ThreadLocalPtrProxy & operator= (ThreadLocalPtrProxy< U > &&other) noexcept
template<typename U >
ThreadLocalPtrProxy & operator= (const ThreadLocalPtrProxy< U > &other) noexcept
Type & operator* () const noexcept
Type * operator-> () const noexcept
Type * Get () const noexcept
operator bool () const noexcept
Type & operator[] (std::size_t i) const
Detailed Description
template<typename Type>
class yaclib::detail::fiber::ThreadLocalPtrProxy< Type >
Definition at line 12 of file thread_local_proxy.hpp.
Constructor & Destructor Documentation
ThreadLocalPtrProxy() [1/6]
template<typename Type > yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::ThreadLocalPtrProxy () inline noexcept
Definition at line 16 of file thread_local_proxy.hpp.
ThreadLocalPtrProxy() [2/6]
template<typename Type > yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::ThreadLocalPtrProxy (Type * value) inline noexcept
Definition at line 19 of file thread_local_proxy.hpp.
References yaclib::MakeContract(), and yaclib::detail::fiber::SetDefault().
ThreadLocalPtrProxy() [3/6]
template<typename Type > yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::ThreadLocalPtrProxy (ThreadLocalPtrProxy< Type > && other) inline noexcept
Definition at line 24 of file thread_local_proxy.hpp.
ThreadLocalPtrProxy() [4/6]
template<typename Type > yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::ThreadLocalPtrProxy (const ThreadLocalPtrProxy< Type > & other) inline noexcept
Definition at line 26 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::GetImpl(), yaclib::MakeContract(), and yaclib::detail::fiber::SetDefault().
ThreadLocalPtrProxy() [5/6]
template<typename Type > template<typename U > yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::ThreadLocalPtrProxy (ThreadLocalPtrProxy< U > && other) inline noexcept
Definition at line 47 of file thread_local_proxy.hpp.
ThreadLocalPtrProxy() [6/6]
template<typename Type > template<typename U > yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::ThreadLocalPtrProxy (const ThreadLocalPtrProxy< U > & other) inline noexcept
Definition at line 50 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::GetImpl(), yaclib::MakeContract(), and yaclib::detail::fiber::SetDefault().
Member Function Documentation
Get()
template<typename Type > Type * yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::Get () const inline noexcept
Definition at line 74 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::GetImpl().
Referenced by yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator bool(), yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator*(), yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator->(), yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator=(), and yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator[]().
operator bool()
template<typename Type > yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator bool () const inline explicit noexcept
Definition at line 78 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::Get().
operator*()
template<typename Type > Type & yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator* () const inline noexcept
Definition at line 65 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::Get(), and yaclib::MakeContract().
operator->()
template<typename Type > Type * yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator-> () const inline noexcept
Definition at line 70 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::Get().
operator=() [1/5]
template<typename Type > ThreadLocalPtrProxy & yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator= (const ThreadLocalPtrProxy< Type > & other) inline noexcept
Definition at line 38 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::Get(), yaclib::detail::fiber::GetImpl(), yaclib::MakeContract(), and yaclib::detail::fiber::SetDefault().
operator=() [2/5]
template<typename Type > template<typename U > ThreadLocalPtrProxy & yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator= (const ThreadLocalPtrProxy< U > & other) inline noexcept
Definition at line 60 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::GetImpl(), yaclib::MakeContract(), and yaclib::detail::fiber::SetDefault().
operator=() [3/5]
template<typename Type > ThreadLocalPtrProxy & yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator= (ThreadLocalPtrProxy< Type > && other) inline noexcept
Definition at line 34 of file thread_local_proxy.hpp.
References yaclib::MakeContract().
operator=() [4/5]
template<typename Type > template<typename U > ThreadLocalPtrProxy & yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator= (ThreadLocalPtrProxy< U > && other) inline noexcept
Definition at line 55 of file thread_local_proxy.hpp.
References yaclib::MakeContract().
operator=() [5/5]
template<typename Type > ThreadLocalPtrProxy & yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator= (Type * value) inline noexcept
Definition at line 30 of file thread_local_proxy.hpp.
References yaclib::MakeContract(), and yaclib::detail::fiber::Set().
operator[]()
template<typename Type > Type & yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::operator[] (std::size_t i) const inline
Definition at line 82 of file thread_local_proxy.hpp.
References yaclib::detail::fiber::ThreadLocalPtrProxy< Type >::Get(), and yaclib::MakeContract().
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/fiber/thread_local_proxy.hpp