YACLib: yaclib::fault::Scheduler Class Reference
yaclib::fault::Scheduler Class Reference final
#include <scheduler.hpp>
Public Member Functions
Scheduler () noexcept=default
void Schedule (detail::fiber::FiberBase *fiber)
bool IsRunning () const noexcept
void Sleep (uint64_t ns)
void SleepPreemptive (uint64_t ns)
uint64_t GetTimeNs () const noexcept
void Stop ()
Static Public Member Functions
static detail::fiber::FiberBase * Current () noexcept
static detail::fiber::FiberBase::Id GetId ()
static void RescheduleCurrent ()
static void SetTickLength (uint32_t tick) noexcept
static void SetRandomListPick (uint32_t k) noexcept
static Scheduler * GetScheduler () noexcept
static void Set (Scheduler *scheduler) noexcept
static void Suspend ()
Detailed Description
Definition at line 20 of file scheduler.hpp.
Constructor & Destructor Documentation
Scheduler()
yaclib::fault::Scheduler::Scheduler () default noexcept
Member Function Documentation
Current()
detail::fiber::FiberBase * yaclib::fault::Scheduler::Current () static noexcept
Definition at line 53 of file scheduler.cpp.
References yaclib::fault::sCurrent.
Referenced by yaclib::detail::fiber::GetImpl(), yaclib::detail::fiber::Thread::joinable(), yaclib::detail::fiber::Set(), and yaclib::detail::fiber::FiberQueue::Wait().
GetId()
detail::fiber::FiberBase::Id yaclib::fault::Scheduler::GetId () static
Definition at line 57 of file scheduler.cpp.
References yaclib::detail::fiber::FiberBase::GetId(), yaclib::fault::sCurrent, and YACLIB_DEBUG.
Referenced by yaclib::detail::fiber::RecursiveMutex::lock(), yaclib::detail::fiber::RecursiveMutex::LockHelper(), and yaclib::detail::fiber::RecursiveMutex::try_lock().
GetScheduler()
Scheduler * yaclib::fault::Scheduler::GetScheduler () static noexcept
Definition at line 35 of file scheduler.cpp.
References yaclib::fault::sCurrentScheduler.
Referenced by yaclib::detail::fiber::Thread::join(), yaclib::detail::fiber::SystemClock::now(), RescheduleCurrent(), yaclib::detail::fiber::ScheduleFiber(), yaclib::detail::fiber::Thread::Thread(), and yaclib::detail::fiber::FiberQueue::Wait().
GetTimeNs()
uint64_t yaclib::fault::Scheduler::GetTimeNs () const noexcept
Definition at line 73 of file scheduler.cpp.
Referenced by yaclib::detail::fiber::SystemClock::now(), and Sleep().
IsRunning()
bool yaclib::fault::Scheduler::IsRunning () const noexcept
Definition at line 21 of file scheduler.cpp.
Referenced by Schedule().
RescheduleCurrent()
void yaclib::fault::Scheduler::RescheduleCurrent () static
Definition at line 108 of file scheduler.cpp.
References GetScheduler(), yaclib::detail::fiber::BiList::PushBack(), and yaclib::fault::sCurrent.
Schedule()
void yaclib::fault::Scheduler::Schedule (detail::fiber::FiberBase * fiber)
Definition at line 43 of file scheduler.cpp.
References IsRunning(), yaclib::detail::fiber::BiList::PushBack(), yaclib::detail::fiber::FiberBase::SetState(), and yaclib::detail::fiber::Waiting.
Referenced by yaclib::detail::fiber::ScheduleFiber(), and yaclib::detail::fiber::Thread::Thread().
Set()
void yaclib::fault::Scheduler::Set (Scheduler * scheduler) static noexcept
Definition at line 39 of file scheduler.cpp.
References yaclib::fault::sCurrentScheduler.
Referenced by Stop().
SetRandomListPick()
void yaclib::fault::Scheduler::SetRandomListPick (uint32_t k) static noexcept
Definition at line 121 of file scheduler.cpp.
References yaclib::fault::sRandomListPick.
Referenced by yaclib::fiber::SetFaultRandomListPick().
SetTickLength()
void yaclib::fault::Scheduler::SetTickLength (uint32_t tick) static noexcept
Definition at line 117 of file scheduler.cpp.
References yaclib::fault::sTickLength.
Referenced by yaclib::fiber::SetFaultTickLength().
Sleep()
void yaclib::fault::Scheduler::Sleep (uint64_t ns)
Definition at line 125 of file scheduler.cpp.
References GetTimeNs(), yaclib::detail::fiber::BiList::PushBack(), yaclib::fault::sCurrent, and Suspend().
Referenced by SleepPreemptive().
SleepPreemptive()
void yaclib::fault::Scheduler::SleepPreemptive (uint64_t ns)
Definition at line 135 of file scheduler.cpp.
References yaclib::GetFaultSleepTime(), yaclib::detail::GetRandNumber(), Sleep(), and YACLIB_DEBUG.
Stop()
void yaclib::fault::Scheduler::Stop ()
Definition at line 30 of file scheduler.cpp.
References Set(), and YACLIB_DEBUG.
Suspend()
void yaclib::fault::Scheduler::Suspend () static
Definition at line 25 of file scheduler.cpp.
References yaclib::fault::sCurrent, and yaclib::detail::fiber::FiberBase::Suspend().
Referenced by yaclib::detail::fiber::Thread::join(), Sleep(), and yaclib::detail::fiber::FiberQueue::Wait().
The documentation for this class was generated from the following files:
include/yaclib/fault/detail/fiber/scheduler.hpp
src/fault/fiber/scheduler.cpp