YACLib: yaclib::detail::AtomicIntegralBase< Impl, T, true > Class Template Reference
yaclib::detail::AtomicIntegralBase< Impl, T, true > Class Template Reference
#include <atomic.hpp>
Public Member Functions
T fetch_and (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
T fetch_and (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T fetch_or (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
T fetch_or (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T fetch_xor (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
T fetch_xor (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T operator++ () noexcept
T operator++ () volatile noexcept
T operator++ (int) noexcept
T operator++ (int) volatile noexcept
T operator-- () noexcept
T operator-- () volatile noexcept
T operator-- (int) noexcept
T operator-- (int) volatile noexcept
T operator&= (T arg) noexcept
T operator&= (T arg) volatile noexcept
T operator|= (T arg) noexcept
T operator|= (T arg) volatile noexcept
T operator^= (T arg) noexcept
T operator^= (T arg) volatile noexcept
Public Member Functions inherited from yaclib::detail::AtomicFloatingBase< Impl, T, true >
T fetch_add (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
T fetch_add (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T fetch_sub (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
T fetch_sub (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T operator+= (T arg) noexcept
T operator+= (T arg) volatile noexcept
T operator-= (T arg) noexcept
T operator-= (T arg) volatile noexcept
Public Member Functions inherited from yaclib::detail::AtomicBase< Impl, T >
T operator= (T desired) noexcept
T operator= (T desired) volatile noexcept
void store (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
void store (T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T load (std::memory_order order=std::memory_order_seq_cst) const noexcept
T load (std::memory_order order=std::memory_order_seq_cst) const volatile noexcept
operator T () const noexcept
operator T () const volatile noexcept
T exchange (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
T exchange (T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Detailed Description
template<typename Impl, typename T>
class yaclib::detail::AtomicIntegralBase< Impl, T, true >
Definition at line 180 of file atomic.hpp.
Member Function Documentation
fetch_and() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::fetch_and (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 186 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_and() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::fetch_and (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 190 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_or() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::fetch_or (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 195 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_or() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::fetch_or (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 199 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_xor() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::fetch_xor (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 204 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
fetch_xor() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::fetch_xor (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 208 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator&=() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator&= (T arg) inline noexcept
Definition at line 249 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator&=() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator&= (T arg) volatile inline noexcept
Definition at line 253 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator++() [1/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator++ () inline noexcept
Definition at line 213 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator++() [2/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator++ () volatile inline noexcept
Definition at line 217 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator++() [3/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator++ (int) inline noexcept
Definition at line 222 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator++() [4/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator++ (int) volatile inline noexcept
Definition at line 226 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator--() [1/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator-- () inline noexcept
Definition at line 231 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator--() [2/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator-- () volatile inline noexcept
Definition at line 235 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator--() [3/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator-- (int) inline noexcept
Definition at line 240 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator--() [4/4]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator-- (int) volatile inline noexcept
Definition at line 244 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator^=() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator^= (T arg) inline noexcept
Definition at line 267 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator^=() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator^= (T arg) volatile inline noexcept
Definition at line 271 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator|=() [1/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator|= (T arg) inline noexcept
Definition at line 258 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
operator|=() [2/2]
template<typename Impl , typename T > T yaclib::detail::AtomicIntegralBase< Impl, T, true >::operator|= (T arg) volatile inline noexcept
Definition at line 262 of file atomic.hpp.
References yaclib::MakeContract(), and YACLIB_INJECT_FAULT.
The documentation for this class was generated from the following file:
include/yaclib/fault/detail/atomic.hpp