YACLib: yaclib::detail::List Class Reference
yaclib::detail::List Class Reference final
#include <intrusive_list.hpp>
Public Member Functions
List & operator= (const List &)=delete
List & operator= (List &&)=delete
List (const List &)=delete
List () noexcept=default
List (List &&) noexcept
void PushFront (Node &node) noexcept
void PushBack (Node &node) noexcept
bool Empty () const noexcept
Node & PopFront () noexcept
Detailed Description
Definition at line 7 of file intrusive_list.hpp.
Constructor & Destructor Documentation
List() [1/3]
yaclib::detail::List::List (const List &) delete
List() [2/3]
yaclib::detail::List::List () default noexcept
List() [3/3]
yaclib::detail::List::List (List && other) noexcept
Definition at line 8 of file intrusive_list.cpp.
References yaclib::MakeContract().
Member Function Documentation
Empty()
bool yaclib::detail::List::Empty () const noexcept
Definition at line 31 of file intrusive_list.cpp.
References yaclib::detail::Node::next, and YACLIB_DEBUG.
Referenced by yaclib::ManualExecutor::Drain(), and PopFront().
operator=() [1/2]
List & yaclib::detail::List::operator= (const List &) delete
operator=() [2/2]
List & yaclib::detail::List::operator= (List &&) delete
PopFront()
Node & yaclib::detail::List::PopFront () noexcept
Definition at line 36 of file intrusive_list.cpp.
References Empty(), yaclib::MakeContract(), yaclib::detail::Node::next, and YACLIB_ASSERT.
Referenced by yaclib::ManualExecutor::Drain().
PushBack()
void yaclib::detail::List::PushBack (Node & node) noexcept
Definition at line 24 of file intrusive_list.cpp.
References yaclib::MakeContract().
PushFront()
void yaclib::detail::List::PushFront (Node & node) noexcept
Definition at line 16 of file intrusive_list.cpp.
References yaclib::Empty, and yaclib::MakeContract().
The documentation for this class was generated from the following files:
include/yaclib/util/detail/intrusive_list.hpp
src/util/intrusive_list.cpp