YACLib: yaclib::detail::fiber::ExecutionContext Class Reference
yaclib::detail::fiber::ExecutionContext Class Reference final
#include <execution_context.hpp>
Public Member Functions
void Setup (Allocation stack, Trampoline trampoline, void *arg)
void Start ()
void SwitchTo (ExecutionContext &other)
void Exit (ExecutionContext &other)
Detailed Description
Definition at line 16 of file execution_context.hpp.
Member Function Documentation
Exit()
void yaclib::detail::fiber::ExecutionContext::Exit (ExecutionContext & other)
Definition at line 33 of file execution_context.cpp.
Referenced by yaclib::detail::fiber::FiberBase::Exit().
Setup()
void yaclib::detail::fiber::ExecutionContext::Setup (Allocation stack, Trampoline trampoline, void * arg)
Definition at line 7 of file execution_context.cpp.
References yaclib::detail::fiber::Allocation::size, and yaclib::detail::fiber::Allocation::start.
Referenced by yaclib::detail::fiber::Fiber< Args >::Fiber().
Start()
void yaclib::detail::fiber::ExecutionContext::Start ()
Definition at line 16 of file execution_context.cpp.
Referenced by yaclib::detail::fiber::FiberBase::Start().
SwitchTo()
void yaclib::detail::fiber::ExecutionContext::SwitchTo (ExecutionContext & other)
Definition at line 22 of file execution_context.cpp.
Referenced by yaclib::detail::fiber::FiberBase::Resume(), and yaclib::detail::fiber::FiberBase::Suspend().
The documentation for this class was generated from the following files:
include/yaclib/fault/detail/fiber/execution_context.hpp
src/fault/fiber/context/execution_context.cpp