YACLib: yaclib::detail::AnyCombinator< V, E, P > Class Template Reference
yaclib::detail::AnyCombinator< V, E, P > Class Template Reference
#include <when_any_impl.hpp>
Public Member Functions
void AddInput (ResultCore< V, E > &input) noexcept
Public Member Functions inherited from yaclib::Job
virtual void Drop () noexcept
Public Member Functions inherited from yaclib::IFunc
virtual void Call () noexcept
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept
Increments reference counter.
virtual void DecRef () noexcept
Decrements reference counter.
virtual ~IRef () noexcept=default
Static Public Member Functions
static auto Make (std::size_t count)
Additional Inherited Members
Public Attributes inherited from yaclib::detail::Node
Node * next = nullptr
Protected Member Functions inherited from yaclib::detail::AnyCombinatorBase< V, E, P >
AnyCombinatorBase (std::size_t, ResultCorePtr< V, E > &&core) noexcept
bool Combine (ResultCore< V, E > &caller) noexcept
Protected Attributes inherited from yaclib::detail::AnyCombinatorBase< V, E, P >
ResultCorePtr< V, E > _core
Detailed Description
template<typename V, typename E, FailPolicy P>
class yaclib::detail::AnyCombinator< V, E, P >
Definition at line 133 of file when_any_impl.hpp.
Member Function Documentation
AddInput()
template<typename V , typename E , FailPolicy P> void yaclib::detail::AnyCombinator< V, E, P >::AddInput (ResultCore< V, E > & input) inline noexcept
Definition at line 147 of file when_any_impl.hpp.
References yaclib::MakeContract().
Make()
template<typename V , typename E , FailPolicy P> static auto yaclib::detail::AnyCombinator< V, E, P >::Make (std::size_t count) inline static
Definition at line 138 of file when_any_impl.hpp.
References yaclib::MakeContract().
Referenced by yaclib::WhenAny().
The documentation for this class was generated from the following file:
include/yaclib/async/detail/when_any_impl.hpp