YACLib: yaclib::detail Namespace Reference
yaclib::detail Namespace Reference
Namespaces
namespace fiber
namespace thread
Classes
struct AsyncTypes
struct AsyncTypes< Future< V, E > >
struct AsyncTypes< FutureBase< V, E > >
struct AsyncTypes< FutureOn< V, E > >
struct AsyncTypes< SharedFuture< V, E > >
struct AsyncTypes< SharedFutureBase< V, E > >
struct AsyncTypes< SharedFutureOn< V, E > >
class Atomic
class Atomic< Impl, U * >
class AtomicBase
struct AtomicCounter
class AtomicEvent
class AtomicFlag
class AtomicFloatingBase
class AtomicFloatingBase< Impl, T, true >
class AtomicIntegralBase
class AtomicIntegralBase< Impl, T, true >
class AtomicWait
struct AwaitAwaiter
struct AwaitAwaiter< Handle, false >
struct AwaitAwaiter< Handle, true >
struct AwaitAwaiterBase
class AwaitEvent
struct AwaitOnAwaiter
class AwaitOnEvent
class AwaitSingleAwaiter
class AwaitSingleAwaiter< false, V, E >
class AwaitSingleAwaiter< true, V, E >
class BaseCore
struct Callback
struct CallCallback
class ConditionVariable
class ConditionVariableAny
class Core
class CurrentAwaiter
struct DefaultDeleter
struct Destroy
struct DropCallback
struct DynamicSharedEvent
struct EventHelperCallback
class FuncCore
class Guard
class GuardAwaiter
class GuardState
class GuardStickyAwaiter
struct Head
struct Head< T, Args... >
class Helper
class Injector
class InlineCore
struct InstantiationTypes
struct InstantiationTypes< Instance, Instance< V, E > >
struct Invoke
struct Invoke< Func, void >
struct IsInstantiationOf
struct IsInstantiationOf< Instance, Instance< Args... > >
struct IsInvocable
struct IsInvocable< Func, void >
class List
class LockAwaiter
class LockStickyAwaiter
class MultiAwaitAwaiter
class MultiAwaitOnAwaiter
struct MultiEvent
class Mutex
class MutexEvent
struct MutexImpl
struct Node
Node class, used in intrusive data structure.
struct NopeBase
struct NopeDeleter
class NoResultCore
struct NoTimeoutTag
class OnAwaiter
struct OneCounter
class PromiseCore
class PromiseType
struct PromiseTypeDeleter
class ReadyCore
class RecursiveMutex
class RecursiveTimedMutex
class ResultCore
struct Return
struct Return< V, E, Func, 1 >
struct Return< V, E, Func, 2 >
struct Return< V, E, Func, 3 >
struct Return< V, E, Func, 4 >
struct Return< V, E, Func, 5 >
class SafeCall
struct SetDeleter
class SharedCore
class SharedFunc
struct SharedHandle
class SharedMutex
struct SharedMutexImpl
class SharedTimedMutex
class Spinlock
class Stack
struct StaticSharedEvent
class TimedMutex
struct TransferAwaiter
struct TransferSingleAwaiter
class UniqueCore
struct UniqueHandle
class UniqueJob
class UnlockAwaiter
class UnlockOnAwaiter
class UnlockStickyAwaiter
class Yield
Typedefs
template<CoreType Type, typename V , typename E >
using ResultCoreT = std::conditional_t< IsDetach(Type), NoResultCore, std::conditional_t< IsToShared(Type), SharedCore< V, E >, UniqueCore< V, E > > >
template<bool SymmetricTransfer>
using Transfer = InlineCore *
template<typename V , typename E >
using SharedCorePtr = IntrusivePtr< SharedCore< V, E > >
template<typename V , typename E >
using UniqueCorePtr = IntrusivePtr< UniqueCore< V, E > >
template<bool Single>
using AwaitOnCounterT = std::conditional_t< Single, OneCounter< NopeBase, NopeDeleter >, AtomicCounter< NopeBase, NopeDeleter > >
template<typename V , typename E , bool Lazy, bool Shared>
using PromiseTypeBase = std::conditional_t< Shared, AtomicCounter< SharedCore< V, E >, PromiseTypeDeleter< Lazy, Shared > >, OneCounter< UniqueCore< V, E >, PromiseTypeDeleter< Lazy, Shared > > >
using DefaultEvent = MutexEvent
Enumerations
enum class CoreType : unsigned char {
None = 0 , Run = 1 << 0 , Detach = 1 << 1 , FromUnique = 1 << 2 ,
FromShared = 1 << 3 , ToUnique = 1 << 4 , ToShared = 1 << 5 , Call = 1 << 6 ,
Lazy = 1 << 7
}
enum class AsyncType { None , Unique , Shared }
enum WaitStatus { Timeout , Ready }
enum class LogLevel : unsigned char { Debug = 0 , Warn = 1 , Count = 3 }
Functions
InlineCore & MakeDrop () noexcept
constexpr CoreType operator| (CoreType a, CoreType b)
constexpr CoreType operator& (CoreType a, CoreType b)
constexpr bool IsRun (CoreType type)
constexpr bool IsDetach (CoreType type)
constexpr bool IsFromUnique (CoreType type)
constexpr bool IsFromShared (CoreType type)
constexpr bool IsToShared (CoreType type)
constexpr bool IsToUnique (CoreType type)
constexpr bool IsCall (CoreType type)
constexpr bool IsLazy (CoreType type)
YACLIB_INLINE BaseCore * MoveToCaller (BaseCore *head) noexcept
template<typename V , typename E , typename Func >
constexpr char Tag () noexcept
template<CoreType CoreT, typename Arg , typename E , typename Func >
auto * MakeCore (Func &&f)
template<CoreType CoreT, bool On, typename FromCorePtr , typename Func >
auto SetCallback (FromCorePtr &&core, IExecutor *executor, Func &&f)
template<bool SymmetricTransfer>
YACLIB_INLINE auto Step (InlineCore &caller, InlineCore &callback) noexcept
template<bool SymmetricTransfer>
YACLIB_INLINE auto Noop () noexcept
YACLIB_INLINE void Loop (InlineCore *prev, InlineCore *curr) noexcept
template<typename Event , typename... Handles>
void SetCallbacksStatic (Event &event, Handles... handles)
template<typename Event , typename It >
void SetCallbacksDynamic (Event &event, It it, std::size_t count)
template<typename Event , typename Timeout , typename Range >
bool WaitRange (Event &event, const Timeout &timeout, Range &&range, std::size_t count) noexcept
template<typename Event , typename Timeout , typename... Handles>
bool WaitCore (const Timeout &timeout, Handles... handles) noexcept
template<typename Event , typename Timeout , typename Iterator >
bool WaitIterator (const Timeout &timeout, Iterator it, std::size_t count) noexcept
template bool WaitCore< DefaultEvent, NoTimeoutTag, UniqueHandle > (const NoTimeoutTag &, UniqueHandle) noexcept
template bool WaitCore< DefaultEvent, NoTimeoutTag, SharedHandle > (const NoTimeoutTag &, SharedHandle) noexcept
template<typename Combinator , typename It >
void WhenImpl (Combinator *combinator, It it, std::size_t count) noexcept
template<typename Combinator , typename E , typename... V>
void WhenImpl (Combinator &combinator, FutureBase< V, E > &&... fs) noexcept
template<bool SymmetricTransfer>
auto WhenSetResult (BaseCore *callback)
template<typename V = Unit, typename E = StopError, typename Func >
YACLIB_INLINE auto Run (IExecutor &e, Func &&f)
template<typename V = Unit, typename E = StopError, typename Func >
YACLIB_INLINE auto RunShared (IExecutor &e, Func &&f)
template<typename Func >
Job * MakeUniqueJob (Func &&f)
bool ShouldFailAtomicWeak ()
void SetAtomicWeakFailFrequency (std::uint32_t k)
constexpr std::cv_status CVStatusFrom (WaitStatus)
constexpr std::cv_status CVStatusFrom (std::cv_status)
template<typename V , typename E , typename Func >
YACLIB_INLINE auto Schedule (IExecutor &e, Func &&f)
void Start (BaseCore *head, IExecutor &e) noexcept
void Start (BaseCore *head) noexcept
void SetCallback (LogLevel level, LogCallback callback) noexcept
void LogMessage (LogLevel level, std::string_view file, std::size_t line, std::string_view func, std::string_view condition, std::string_view message) noexcept
void SetSeed (std::uint32_t new_seed)
std::uint32_t GetSeed ()
std::uint64_t GetRandNumber (std::uint64_t max)
std::uint64_t GetRandCount ()
void ForwardToRandCount (std::uint64_t random_count)
Variables
constexpr std::size_t kSharedRefWithFuture = 4
constexpr std::size_t kSharedRefNoFuture = 3
static std::uint32_t sAtomicFailFrequency = 13
static std::uint32_t sYieldFrequency = 16
static std::uint32_t sSleepTime = 100
static std::uint64_t sInjectedCount = 0
static std::uint32_t sSeed = 1239
static thread_local std::mt19937_64 eng {sSeed}
static std::array< LogCallback, static_cast< std::size_t >(LogLevel::Count)> sCallbacks = {}
Typedef Documentation
AwaitOnCounterT
template<bool Single> using yaclib::detail::AwaitOnCounterT = typedef std::conditional_t<Single, OneCounter<NopeBase, NopeDeleter>, AtomicCounter<NopeBase, NopeDeleter> >
Definition at line 15 of file await_on_awaiter.hpp.
DefaultEvent
using yaclib::detail::DefaultEvent = typedef MutexEvent
Definition at line 16 of file default_event.hpp.
PromiseTypeBase
template<typename V , typename E , bool Lazy, bool Shared> using yaclib::detail::PromiseTypeBase = typedef std::conditional_t<Shared, AtomicCounter<SharedCore<V, E>, PromiseTypeDeleter<Lazy, Shared> >, OneCounter<UniqueCore<V, E>, PromiseTypeDeleter<Lazy, Shared> >>
Definition at line 46 of file promise_type.hpp.
ResultCoreT
template<CoreType Type, typename V , typename E > using yaclib::detail::ResultCoreT = typedef std::conditional_t<IsDetach(Type), NoResultCore, std::conditional_t<IsToShared(Type), SharedCore<V, E>, UniqueCore<V, E> >>
Definition at line 91 of file core.hpp.
SharedCorePtr
template<typename V , typename E > using yaclib::detail::SharedCorePtr = typedef IntrusivePtr<SharedCore<V, E> >
Definition at line 55 of file shared_core.hpp.
Transfer
template<bool SymmetricTransfer> using yaclib::detail::Transfer = typedef InlineCore*
Definition at line 58 of file inline_core.hpp.
UniqueCorePtr
template<typename V , typename E > using yaclib::detail::UniqueCorePtr = typedef IntrusivePtr<UniqueCore<V, E> >
Definition at line 65 of file unique_core.hpp.
Enumeration Type Documentation
AsyncType
enum class yaclib::detail::AsyncType strong
Enumerator
None
Unique
Shared
Definition at line 104 of file core.hpp.
CoreType
enum class yaclib::detail::CoreType : unsigned char strong
Enumerator
None
Run
Detach
FromUnique
FromShared
ToUnique
ToShared
Call
Lazy
Definition at line 38 of file core.hpp.
LogLevel
enum class yaclib::detail::LogLevel : unsigned char strong
Enumerator
Debug
Warn
Count
Definition at line 14 of file log.hpp.
WaitStatus
enum yaclib::detail::WaitStatus
Enumerator
Timeout
Ready
Definition at line 5 of file wait_status.hpp.
Function Documentation
CVStatusFrom() [1/2]
constexpr std::cv_status yaclib::detail::CVStatusFrom (std::cv_status status) constexpr
Definition at line 12 of file condition_variable.cpp.
References yaclib::MakeContract().
CVStatusFrom() [2/2]
constexpr std::cv_status yaclib::detail::CVStatusFrom (WaitStatus status) constexpr
Definition at line 5 of file condition_variable.cpp.
References yaclib::MakeContract(), and Ready.
Referenced by yaclib::detail::ConditionVariable< Impl >::wait_for(), and yaclib::detail::ConditionVariable< Impl >::wait_until().
ForwardToRandCount()
void yaclib::detail::ForwardToRandCount (std::uint64_t random_count)
Definition at line 37 of file util.cpp.
References GetRandNumber(), and yaclib::MakeContract().
Referenced by yaclib::fiber::ForwardToFaultRandomCount().
GetRandCount()
std::uint64_t yaclib::detail::GetRandCount ()
Definition at line 29 of file util.cpp.
References yaclib::MakeContract().
Referenced by yaclib::fiber::GetFaultRandomCount().
GetRandNumber()
std::uint64_t yaclib::detail::GetRandNumber (std::uint64_t max)
Definition at line 22 of file util.cpp.
References eng, and yaclib::MakeContract().
Referenced by ForwardToRandCount(), yaclib::detail::Injector::MaybeInject(), yaclib::detail::fiber::PollRandomElementFromList(), ShouldFailAtomicWeak(), yaclib::fault::Scheduler::SleepPreemptive(), and yaclib::detail::fiber::SharedMutex::unlock().
GetSeed()
std::uint32_t yaclib::detail::GetSeed ()
Definition at line 18 of file util.cpp.
References sSeed.
Referenced by yaclib::detail::thread::RandomDevice::reset().
IsCall()
constexpr bool yaclib::detail::IsCall (CoreType type) constexpr
Definition at line 82 of file core.hpp.
References Call, and yaclib::MakeContract().
IsDetach()
constexpr bool yaclib::detail::IsDetach (CoreType type) constexpr
Definition at line 62 of file core.hpp.
References Detach, and yaclib::MakeContract().
Referenced by MakeCore(), and SetCallback().
IsFromShared()
constexpr bool yaclib::detail::IsFromShared (CoreType type) constexpr
Definition at line 70 of file core.hpp.
References FromShared, and yaclib::MakeContract().
IsFromUnique()
constexpr bool yaclib::detail::IsFromUnique (CoreType type) constexpr
Definition at line 66 of file core.hpp.
References FromUnique, and yaclib::MakeContract().
IsLazy()
constexpr bool yaclib::detail::IsLazy (CoreType type) constexpr
Definition at line 86 of file core.hpp.
References Lazy, and yaclib::MakeContract().
Referenced by SetCallback().
IsRun()
constexpr bool yaclib::detail::IsRun (CoreType type) constexpr
Definition at line 58 of file core.hpp.
References yaclib::MakeContract(), and Run.
Referenced by MakeCore().
IsToShared()
constexpr bool yaclib::detail::IsToShared (CoreType type) constexpr
Definition at line 74 of file core.hpp.
References yaclib::MakeContract(), and ToShared.
Referenced by MakeCore().
IsToUnique()
constexpr bool yaclib::detail::IsToUnique (CoreType type) constexpr
Definition at line 78 of file core.hpp.
References yaclib::MakeContract(), and ToUnique.
LogMessage()
void yaclib::detail::LogMessage (LogLevel level, std::string_view file, std::size_t line, std::string_view func, std::string_view condition, std::string_view message) noexcept
Definition at line 10 of file log.cpp.
References yaclib::MakeContract(), and sCallbacks.
Loop()
YACLIB_INLINE void yaclib::detail::Loop (InlineCore * prev, InlineCore * curr) noexcept
Definition at line 46 of file inline_core.hpp.
References yaclib::detail::InlineCore::Here(), and yaclib::MakeContract().
Referenced by yaclib::detail::Destroy::await_suspend(), yaclib::detail::TransferAwaiter::await_suspend(), yaclib::detail::TransferSingleAwaiter< V, E >::await_suspend(), yaclib::detail::ReadyCore< V, E >::Call(), yaclib::Promise< V, E >::Set(), SetCallback(), yaclib::detail::BaseCore::SetResultImpl(), and WhenSetResult().
MakeCore()
template<CoreType CoreT, typename Arg , typename E , typename Func > auto * yaclib::detail::MakeCore (Func && f)
Definition at line 363 of file core.hpp.
References IsDetach(), IsRun(), IsToShared(), kSharedRefWithFuture, yaclib::MakeContract(), None, Shared, and Unique.
MakeDrop()
InlineCore & yaclib::detail::MakeDrop () noexcept
Definition at line 27 of file drop_core.cpp.
References yaclib::MakeContract().
Referenced by yaclib::FutureBase< V, E >::Detach(), yaclib::Task< V, E >::Detach(), yaclib::Task< V, E >::Detach(), and SetCallback().
MakeUniqueJob()
template<typename Func > Job * yaclib::detail::MakeUniqueJob (Func && f)
Definition at line 32 of file unique_job.hpp.
References yaclib::MakeContract().
Referenced by yaclib::Submit().
MoveToCaller()
YACLIB_INLINE BaseCore * yaclib::detail::MoveToCaller (BaseCore * head) noexcept
Definition at line 94 of file core.hpp.
References yaclib::MakeContract(), yaclib::detail::Node::next, and YACLIB_ASSERT.
Referenced by yaclib::detail::TransferAwaiter::await_suspend(), yaclib::detail::TransferSingleAwaiter< V, E >::await_suspend(), Start(), and Start().
Noop()
template<bool SymmetricTransfer> YACLIB_INLINE auto yaclib::detail::Noop () noexcept
Definition at line 35 of file inline_core.hpp.
References yaclib::MakeContract(), and yaclib_std::noop_coroutine().
operator&()
constexpr CoreType yaclib::detail::operator& (CoreType a, CoreType b) inline constexpr
Definition at line 54 of file core.hpp.
References yaclib::MakeContract().
operator|()
constexpr CoreType yaclib::detail::operator| (CoreType a, CoreType b) inline constexpr
Definition at line 50 of file core.hpp.
References yaclib::MakeContract().
Run()
template<typename V = Unit, typename E = StopError, typename Func > YACLIB_INLINE auto yaclib::detail::Run (IExecutor & e, Func && f)
Definition at line 15 of file run.hpp.
References Call, yaclib::MakeContract(), Run, and ToUnique.
RunShared()
template<typename V = Unit, typename E = StopError, typename Func > YACLIB_INLINE auto yaclib::detail::RunShared (IExecutor & e, Func && f)
Definition at line 32 of file run.hpp.
References Call, kSharedRefWithFuture, yaclib::MakeContract(), Run, and ToShared.
Schedule()
template<typename V , typename E , typename Func > YACLIB_INLINE auto yaclib::detail::Schedule (IExecutor & e, Func && f)
Definition at line 9 of file schedule.hpp.
References Call, yaclib::MakeContract(), Run, and ToUnique.
SetAtomicWeakFailFrequency()
void yaclib::detail::SetAtomicWeakFailFrequency (std::uint32_t k)
Definition at line 16 of file atomic.cpp.
References yaclib::MakeContract(), and sAtomicFailFrequency.
Referenced by yaclib::SetAtomicFailFrequency().
SetCallback() [1/2]
template<CoreType CoreT, bool On, typename FromCorePtr , typename Func > auto yaclib::detail::SetCallback (FromCorePtr && core, IExecutor * executor, Func && f)
Definition at line 389 of file core.hpp.
References FromShared, FromUnique, IsDetach(), IsLazy(), Loop(), yaclib::MakeContract(), MakeDrop(), yaclib::On(), Shared, Unique, and YACLIB_ASSERT.
SetCallback() [2/2]
void yaclib::detail::SetCallback (LogLevel level, LogCallback callback) noexcept
Definition at line 17 of file log.cpp.
References yaclib::MakeContract(), and sCallbacks.
SetCallbacksDynamic()
template<typename Event , typename It > void yaclib::detail::SetCallbacksDynamic (Event & event, It it, std::size_t count)
Definition at line 87 of file shared_event.hpp.
References yaclib::MakeContract(), and YACLIB_ASSERT.
SetCallbacksStatic()
template<typename Event , typename... Handles> void yaclib::detail::SetCallbacksStatic (Event & event, Handles... handles)
Definition at line 63 of file shared_event.hpp.
References yaclib::MakeContract().
SetSeed()
void yaclib::detail::SetSeed (std::uint32_t new_seed)
Definition at line 13 of file util.cpp.
References eng, yaclib::MakeContract(), and sSeed.
Referenced by yaclib::SetSeed().
ShouldFailAtomicWeak()
bool yaclib::detail::ShouldFailAtomicWeak ()
Definition at line 11 of file atomic.cpp.
References GetRandNumber(), yaclib::MakeContract(), and sAtomicFailFrequency.
Referenced by yaclib::detail::AtomicBase< Impl, T >::compare_exchange_weak(), yaclib::detail::AtomicBase< Impl, T >::compare_exchange_weak(), yaclib::detail::AtomicBase< Impl, T >::compare_exchange_weak(), and yaclib::detail::AtomicBase< Impl, T >::compare_exchange_weak().
Start() [1/2]
void yaclib::detail::Start (BaseCore * head) noexcept
Definition at line 12 of file task_impl.cpp.
References yaclib::MakeContract(), and MoveToCaller().
Start() [2/2]
void yaclib::detail::Start (BaseCore * head, IExecutor & e) noexcept
Definition at line 6 of file task_impl.cpp.
References yaclib::MakeContract(), and MoveToCaller().
Referenced by yaclib::Task< V, E >::Detach(), yaclib::Task< V, E >::Detach(), yaclib::Task< V, E >::ToFuture(), and yaclib::Task< V, E >::ToFuture().
Step()
template<bool SymmetricTransfer> YACLIB_INLINE auto yaclib::detail::Step (InlineCore & caller, InlineCore & callback) noexcept
Definition at line 23 of file inline_core.hpp.
References yaclib::MakeContract().
Tag()
template<typename V , typename E , typename Func > constexpr char yaclib::detail::Tag () constexpr noexcept
Definition at line 318 of file core.hpp.
References yaclib::MakeContract().
WaitCore()
template<typename Event , typename Timeout , typename... Handles> bool yaclib::detail::WaitCore (const Timeout & timeout, Handles... handles) noexcept
Definition at line 65 of file wait_impl.hpp.
References yaclib::kCount, yaclib::MakeContract(), and WaitRange().
WaitCore< DefaultEvent, NoTimeoutTag, SharedHandle >()
template bool yaclib::detail::WaitCore< DefaultEvent, NoTimeoutTag, SharedHandle > (const NoTimeoutTag & , SharedHandle) extern noexcept
WaitCore< DefaultEvent, NoTimeoutTag, UniqueHandle >()
template bool yaclib::detail::WaitCore< DefaultEvent, NoTimeoutTag, UniqueHandle > (const NoTimeoutTag & , UniqueHandle) extern noexcept
WaitIterator()
template<typename Event , typename Timeout , typename Iterator > bool yaclib::detail::WaitIterator (const Timeout & timeout, Iterator it, std::size_t count) noexcept
Definition at line 86 of file wait_impl.hpp.
References yaclib::MakeContract(), WaitRange(), and YACLIB_ASSERT.
WaitRange()
template<typename Event , typename Timeout , typename Range > bool yaclib::detail::WaitRange (Event & event, const Timeout & timeout, Range && range, std::size_t count) noexcept
Definition at line 20 of file wait_impl.hpp.
References yaclib::MakeContract().
Referenced by WaitCore(), and WaitIterator().
WhenImpl() [1/2]
template<typename Combinator , typename E , typename... V> void yaclib::detail::WhenImpl (Combinator & combinator, FutureBase< V, E > &&... fs) noexcept
Definition at line 22 of file when_impl.hpp.
References yaclib::MakeContract(), and YACLIB_ASSERT.
WhenImpl() [2/2]
template<typename Combinator , typename It > void yaclib::detail::WhenImpl (Combinator * combinator, It it, std::size_t count) noexcept
Definition at line 13 of file when_impl.hpp.
References yaclib::MakeContract(), and YACLIB_ASSERT.
WhenSetResult()
template<bool SymmetricTransfer> auto yaclib::detail::WhenSetResult (BaseCore * callback)
Definition at line 29 of file when_impl.hpp.
References Loop(), yaclib::MakeContract(), and yaclib::detail::UniqueHandle::SetResult().
Variable Documentation
eng
thread_local std::mt19937_64 yaclib::detail::eng {sSeed} static
Definition at line 11 of file util.cpp.
Referenced by GetRandNumber(), and SetSeed().
kSharedRefNoFuture
constexpr std::size_t yaclib::detail::kSharedRefNoFuture = 3 inline constexpr
Definition at line 10 of file shared_core.hpp.
Referenced by yaclib::MakeSharedPromise().
kSharedRefWithFuture
constexpr std::size_t yaclib::detail::kSharedRefWithFuture = 4 inline constexpr
Definition at line 9 of file shared_core.hpp.
Referenced by MakeCore(), yaclib::MakeSharedContract(), yaclib::MakeSharedContractOn(), yaclib::detail::PromiseType< V, E, Lazy, Shared >::PromiseType(), and RunShared().
sAtomicFailFrequency
std::uint32_t yaclib::detail::sAtomicFailFrequency = 13 static
Definition at line 9 of file atomic.cpp.
Referenced by SetAtomicWeakFailFrequency(), and ShouldFailAtomicWeak().
sCallbacks
std::array<LogCallback, static_cast<std::size_t>(LogLevel::Count)> yaclib::detail::sCallbacks = {} static
Definition at line 8 of file log.cpp.
Referenced by LogMessage(), and SetCallback().
sInjectedCount
std::uint64_t yaclib::detail::sInjectedCount = 0 static
Definition at line 11 of file injector.cpp.
Referenced by yaclib::detail::Injector::GetInjectedCount(), and yaclib::detail::Injector::MaybeInject().
sSeed
std::uint32_t yaclib::detail::sSeed = 1239 static
Definition at line 5 of file util.cpp.
Referenced by GetSeed(), and SetSeed().
sSleepTime
std::uint32_t yaclib::detail::sSleepTime = 100 static
Definition at line 10 of file injector.cpp.
Referenced by yaclib::detail::Injector::GetSleepTime(), yaclib::detail::Injector::MaybeInject(), and yaclib::detail::Injector::SetSleepTime().
sYieldFrequency
std::uint32_t yaclib::detail::sYieldFrequency = 16 static
Definition at line 9 of file injector.cpp.
Referenced by yaclib::detail::Injector::SetFrequency().