YACLib: yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO > Struct Template Reference
yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO > Struct Template Reference
#include <shared_mutex.hpp>
Public Member Functions
bool TryLockSharedAwait () noexcept
bool TryLockAwait () noexcept
bool AwaitLockShared (BaseCore &curr) noexcept
bool AwaitLock (BaseCore &curr) noexcept
bool TryLockShared () noexcept
bool TryLock () noexcept
void UnlockHereShared () noexcept
void UnlockHere () noexcept
Detailed Description
template<bool FIFO, bool ReadersFIFO>
struct yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >
Definition at line 17 of file shared_mutex.hpp.
Member Function Documentation
AwaitLock()
template<bool FIFO, bool ReadersFIFO> bool yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::AwaitLock (BaseCore & curr) inline noexcept
Definition at line 40 of file shared_mutex.hpp.
References yaclib::MakeContract(), and yaclib::detail::Node::next.
AwaitLockShared()
template<bool FIFO, bool ReadersFIFO> bool yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::AwaitLockShared (BaseCore & curr) inline noexcept
Definition at line 28 of file shared_mutex.hpp.
References yaclib::MakeContract(), and YACLIB_ASSERT.
TryLock()
template<bool FIFO, bool ReadersFIFO> bool yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::TryLock () inline noexcept
Definition at line 67 of file shared_mutex.hpp.
References yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::TryLockAwait().
TryLockAwait()
template<bool FIFO, bool ReadersFIFO> bool yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::TryLockAwait () inline noexcept
Definition at line 22 of file shared_mutex.hpp.
References yaclib::MakeContract().
Referenced by yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::TryLock().
TryLockShared()
template<bool FIFO, bool ReadersFIFO> bool yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::TryLockShared () inline noexcept
Definition at line 57 of file shared_mutex.hpp.
References yaclib::MakeContract().
TryLockSharedAwait()
template<bool FIFO, bool ReadersFIFO> bool yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::TryLockSharedAwait () inline noexcept
Definition at line 18 of file shared_mutex.hpp.
UnlockHere()
template<bool FIFO, bool ReadersFIFO> void yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::UnlockHere () inline noexcept
Definition at line 81 of file shared_mutex.hpp.
References yaclib::MakeContract().
UnlockHereShared()
template<bool FIFO, bool ReadersFIFO> void yaclib::detail::SharedMutexImpl< FIFO, ReadersFIFO >::UnlockHereShared () inline noexcept
Definition at line 71 of file shared_mutex.hpp.
References yaclib::MakeContract(), and yaclib::detail::Run.
The documentation for this struct was generated from the following file:
include/yaclib/coro/shared_mutex.hpp