YACLib: yaclib::detail::fiber::SystemClock Struct Reference
yaclib::detail::fiber::SystemClock Struct Reference
#include <system_clock.hpp>
Public Types
using duration = std::chrono::nanoseconds
using rep = duration::rep
using period = duration::period
using time_point = std::chrono::time_point< SystemClock >
Static Public Member Functions
static time_point now ()
static time_t to_time_t (const time_point &time_point) noexcept
static time_point from_time_t (time_t c_time_point) noexcept
Static Public Attributes
static constexpr bool is_steady = true
Detailed Description
Definition at line 9 of file system_clock.hpp.
Member Typedef Documentation
duration
using yaclib::detail::fiber::SystemClock::duration = std::chrono::nanoseconds
Definition at line 10 of file system_clock.hpp.
period
using yaclib::detail::fiber::SystemClock::period = duration::period
Definition at line 12 of file system_clock.hpp.
rep
using yaclib::detail::fiber::SystemClock::rep = duration::rep
Definition at line 11 of file system_clock.hpp.
time_point
using yaclib::detail::fiber::SystemClock::time_point = std::chrono::time_point<SystemClock>
Definition at line 13 of file system_clock.hpp.
Member Function Documentation
from_time_t()
SystemClock::time_point yaclib::detail::fiber::SystemClock::from_time_t (time_t c_time_point) static noexcept
Definition at line 14 of file system_clock.cpp.
References yaclib::MakeContract().
now()
SystemClock::time_point yaclib::detail::fiber::SystemClock::now () static
Definition at line 5 of file system_clock.cpp.
References yaclib::fault::Scheduler::GetScheduler(), and yaclib::fault::Scheduler::GetTimeNs().
Referenced by yaclib::detail::fiber::FiberQueue::Wait().
to_time_t()
time_t yaclib::detail::fiber::SystemClock::to_time_t (const time_point & time_point) static noexcept
Definition at line 9 of file system_clock.cpp.
Member Data Documentation
is_steady
constexpr bool yaclib::detail::fiber::SystemClock::is_steady = true static constexpr
Definition at line 15 of file system_clock.hpp.
The documentation for this struct was generated from the following files:
include/yaclib/fault/detail/fiber/system_clock.hpp
src/fault/fiber/system_clock.cpp