YACLib: yaclib::detail::AtomicCounter< CounterBase, Deleter > Struct Template Reference
yaclib::detail::AtomicCounter< CounterBase, Deleter > Struct Template Reference final
#include <atomic_counter.hpp>
Public Member Functions
template<typename... Args>
AtomicCounter (std::size_t n, Args &&... args) noexcept(std::is_nothrow_constructible_v< CounterBase, Args... >)
void IncRef () noexcept final
void DecRef () noexcept final
YACLIB_INLINE void IncRef (std::size_t delta) noexcept
YACLIB_INLINE void DecRef (std::size_t delta) noexcept
std::size_t GetRef () const noexcept
YACLIB_INLINE bool SubEqual (std::size_t n) noexcept
Public Attributes
yaclib_std::atomic_size_t count
Detailed Description
template<typename CounterBase, typename Deleter = DefaultDeleter>
struct yaclib::detail::AtomicCounter< CounterBase, Deleter >
Definition at line 13 of file atomic_counter.hpp.
Constructor & Destructor Documentation
AtomicCounter()
template<typename CounterBase , typename Deleter = DefaultDeleter> template<typename... Args> yaclib::detail::AtomicCounter< CounterBase, Deleter >::AtomicCounter (std::size_t n, Args &&... args) inline noexcept
Definition at line 15 of file atomic_counter.hpp.
Member Function Documentation
DecRef() [1/2]
template<typename CounterBase , typename Deleter = DefaultDeleter> void yaclib::detail::AtomicCounter< CounterBase, Deleter >::DecRef () inline final noexcept
Definition at line 23 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::DecRef().
Referenced by yaclib::detail::AtomicCounter< CounterBase, Deleter >::DecRef().
DecRef() [2/2]
template<typename CounterBase , typename Deleter = DefaultDeleter> YACLIB_INLINE void yaclib::detail::AtomicCounter< CounterBase, Deleter >::DecRef (std::size_t delta) inline noexcept
Definition at line 31 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::SubEqual().
GetRef()
template<typename CounterBase , typename Deleter = DefaultDeleter> std::size_t yaclib::detail::AtomicCounter< CounterBase, Deleter >::GetRef () const inline noexcept
Definition at line 37 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::count.
Referenced by yaclib::detail::AwaitAwaiter::await_ready().
IncRef() [1/2]
template<typename CounterBase , typename Deleter = DefaultDeleter> void yaclib::detail::AtomicCounter< CounterBase, Deleter >::IncRef () inline final noexcept
Definition at line 19 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::IncRef().
Referenced by yaclib::detail::AtomicCounter< CounterBase, Deleter >::IncRef().
IncRef() [2/2]
template<typename CounterBase , typename Deleter = DefaultDeleter> YACLIB_INLINE void yaclib::detail::AtomicCounter< CounterBase, Deleter >::IncRef (std::size_t delta) inline noexcept
Definition at line 27 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::count.
SubEqual()
template<typename CounterBase , typename Deleter = DefaultDeleter> YACLIB_INLINE bool yaclib::detail::AtomicCounter< CounterBase, Deleter >::SubEqual (std::size_t n) inline noexcept
Definition at line 42 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::count.
Referenced by yaclib::detail::AwaitAwaiter::await_suspend(), and yaclib::detail::AtomicCounter< CounterBase, Deleter >::DecRef().
Member Data Documentation
count
template<typename CounterBase , typename Deleter = DefaultDeleter> yaclib_std::atomic_size_t yaclib::detail::AtomicCounter< CounterBase, Deleter >::count
Definition at line 56 of file atomic_counter.hpp.
Referenced by yaclib::detail::AwaitAwaiter::AwaitAwaiter(), yaclib::detail::AtomicCounter< CounterBase, Deleter >::GetRef(), yaclib::detail::AtomicCounter< CounterBase, Deleter >::IncRef(), and yaclib::detail::AtomicCounter< CounterBase, Deleter >::SubEqual().
The documentation for this struct was generated from the following file:
include/yaclib/util/detail/atomic_counter.hpp