YACLib: yaclib::when::StaticCombinator< Strategy, Cores > Struct Template Reference
yaclib::when::StaticCombinator< Strategy, Cores > Struct Template Reference
#include <when.hpp>
Public Member Functions
StaticCombinator (std::size_t count, typename Strategy::PromiseType p)
void Set (Cores &... cores)
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept
Increments reference counter.
virtual void DecRef () noexcept
Decrements reference counter.
virtual std::size_t GetRef () noexcept
virtual ~IRef () noexcept=default
Public Attributes
Strategy st
Callbacks callbacks
Detailed Description
template<typename Strategy, typename... Cores>
struct yaclib::when::StaticCombinator< Strategy, Cores >
Definition at line 203 of file when.hpp.
Constructor & Destructor Documentation
StaticCombinator()
template<typename Strategy , typename... Cores> yaclib::when::StaticCombinator< Strategy, Cores >::StaticCombinator (std::size_t count, typename Strategy::PromiseType p) inline
Definition at line 271 of file when.hpp.
References yaclib::when::StaticCombinator< Strategy, Cores >::callbacks, and yaclib::MakeContract().
Member Function Documentation
Set()
template<typename Strategy , typename... Cores> void yaclib::when::StaticCombinator< Strategy, Cores >::Set (Cores &... cores) inline
Definition at line 280 of file when.hpp.
References yaclib::MakeContract().
Referenced by yaclib::when::When().
Member Data Documentation
callbacks
template<typename Strategy , typename... Cores> Callbacks yaclib::when::StaticCombinator< Strategy, Cores >::callbacks
Definition at line 285 of file when.hpp.
Referenced by yaclib::when::StaticCombinator< Strategy, Cores >::StaticCombinator().
st
template<typename Strategy , typename... Cores> Strategy yaclib::when::StaticCombinator< Strategy, Cores >::st
Definition at line 284 of file when.hpp.
The documentation for this struct was generated from the following file:
include/yaclib/async/when/when.hpp