YACLib: yaclib::detail::MutexImpl< FIFO, Batching > Struct Template Reference
yaclib::detail::MutexImpl< FIFO, Batching > Struct Template Reference
#include <mutex.hpp>
Public Member Functions
bool TryLockAwait () noexcept
bool AwaitLock (BaseCore &curr) noexcept
bool TryUnlockAwait () noexcept
YACLIB_INLINE bool BatchingPossible () const noexcept
void UnlockHereAwait () noexcept
auto AwaitUnlock (BaseCore &curr) noexcept
auto AwaitUnlockOn (BaseCore &curr, IExecutor &executor) noexcept
bool TryLock () noexcept
void UnlockHere () noexcept
Detailed Description
template<bool FIFO, bool Batching>
struct yaclib::detail::MutexImpl< FIFO, Batching >
Definition at line 16 of file mutex.hpp.
Member Function Documentation
AwaitLock()
template<bool FIFO, bool Batching> bool yaclib::detail::MutexImpl< FIFO, Batching >::AwaitLock (BaseCore & curr) inline noexcept
Definition at line 24 of file mutex.hpp.
References yaclib::MakeContract().
AwaitUnlock()
template<bool FIFO, bool Batching> auto yaclib::detail::MutexImpl< FIFO, Batching >::AwaitUnlock (BaseCore & curr) inline noexcept
Definition at line 63 of file mutex.hpp.
References yaclib::detail::BaseCore::_executor, yaclib::MakeContract(), yaclib::IntrusivePtr< T >::Swap(), YACLIB_ASSERT, and YACLIB_TRANSFER.
AwaitUnlockOn()
template<bool FIFO, bool Batching> auto yaclib::detail::MutexImpl< FIFO, Batching >::AwaitUnlockOn (BaseCore & curr, IExecutor & executor) inline noexcept
Definition at line 74 of file mutex.hpp.
References yaclib::detail::BaseCore::_executor, yaclib::MakeContract(), yaclib::IExecutor::Submit(), yaclib::detail::MutexImpl< FIFO, Batching >::TryUnlockAwait(), YACLIB_ASSERT, YACLIB_SUSPEND, and YACLIB_TRANSFER.
BatchingPossible()
template<bool FIFO, bool Batching> YACLIB_INLINE bool yaclib::detail::MutexImpl< FIFO, Batching >::BatchingPossible () const inline noexcept
Definition at line 52 of file mutex.hpp.
References yaclib::MakeContract().
TryLock()
template<bool FIFO, bool Batching> bool yaclib::detail::MutexImpl< FIFO, Batching >::TryLock () inline noexcept
Definition at line 97 of file mutex.hpp.
References yaclib::detail::MutexImpl< FIFO, Batching >::TryLockAwait().
TryLockAwait()
template<bool FIFO, bool Batching> bool yaclib::detail::MutexImpl< FIFO, Batching >::TryLockAwait () inline noexcept
Definition at line 17 of file mutex.hpp.
References yaclib::MakeContract().
Referenced by yaclib::detail::MutexImpl< FIFO, Batching >::TryLock().
TryUnlockAwait()
template<bool FIFO, bool Batching> bool yaclib::detail::MutexImpl< FIFO, Batching >::TryUnlockAwait () inline noexcept
Definition at line 42 of file mutex.hpp.
References yaclib::MakeContract(), and YACLIB_ASSERT.
Referenced by yaclib::detail::MutexImpl< FIFO, Batching >::AwaitUnlockOn(), and yaclib::detail::MutexImpl< FIFO, Batching >::UnlockHere().
UnlockHere()
template<bool FIFO, bool Batching> void yaclib::detail::MutexImpl< FIFO, Batching >::UnlockHere () inline noexcept
Definition at line 101 of file mutex.hpp.
References yaclib::detail::MutexImpl< FIFO, Batching >::TryUnlockAwait(), and yaclib::detail::MutexImpl< FIFO, Batching >::UnlockHereAwait().
UnlockHereAwait()
template<bool FIFO, bool Batching> void yaclib::detail::MutexImpl< FIFO, Batching >::UnlockHereAwait () inline noexcept
Definition at line 56 of file mutex.hpp.
References yaclib::detail::BaseCore::_executor, and yaclib::IExecutor::Submit().
Referenced by yaclib::detail::MutexImpl< FIFO, Batching >::UnlockHere().
The documentation for this struct was generated from the following file:
include/yaclib/coro/mutex.hpp