YACLib: yaclib::when::DynamicCombinator< Strategy, Core > Struct Template Reference
yaclib::when::DynamicCombinator< Strategy, Core > Struct Template Reference
#include <when.hpp>
Public Member Functions
DynamicCombinator (std::size_t count, typename Strategy::PromiseType p)
template<typename Iterator >
void Set (Iterator begin, std::size_t count)
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept
Increments reference counter.
virtual void DecRef () noexcept
Decrements reference counter.
virtual std::size_t GetRef () noexcept
virtual ~IRef () noexcept=default
Public Attributes
Strategy st
std::vector< CombinatorCallback< DynamicCombinator, Core, kDynamicTag > > callbacks
Detailed Description
template<typename Strategy, typename Core>
struct yaclib::when::DynamicCombinator< Strategy, Core >
Definition at line 289 of file when.hpp.
Constructor & Destructor Documentation
DynamicCombinator()
template<typename Strategy , typename Core > yaclib::when::DynamicCombinator< Strategy, Core >::DynamicCombinator (std::size_t count, typename Strategy::PromiseType p) inline
Definition at line 290 of file when.hpp.
Member Function Documentation
Set()
template<typename Strategy , typename Core > template<typename Iterator > void yaclib::when::DynamicCombinator< Strategy, Core >::Set (Iterator begin, std::size_t count) inline
Definition at line 295 of file when.hpp.
References yaclib::when::Consume(), yaclib::MakeContract(), and yaclib::Owned.
Referenced by yaclib::when::When().
Member Data Documentation
callbacks
template<typename Strategy , typename Core > std::vector<CombinatorCallback<DynamicCombinator, Core, kDynamicTag> > yaclib::when::DynamicCombinator< Strategy, Core >::callbacks
Definition at line 313 of file when.hpp.
st
template<typename Strategy , typename Core > Strategy yaclib::when::DynamicCombinator< Strategy, Core >::st
Definition at line 312 of file when.hpp.
The documentation for this struct was generated from the following file:
include/yaclib/async/when/when.hpp